### ISSUE TITLE
Android Scrobbling not working

### ISSUE THREAD

**Issue by jbmfg** [krateng/maloja#100]
I cannot get scrobbling from simple scrobbler or pano scrobble to work.  I have tried multiple urls and api keys and it just refuses to scrobble in simple scrobbler and pano will not pass the verify step.  I have confirmed that the api is working by manually checking the "validate-token" service:

`import requests

url = "http://192.168.0.107:42010/api/s/listenbrainz/1/validate-token"
headers = {"Authorization":"Token P5oCuuTB4SvACk9mctMciVQ6M6W9lRw2TQUaz0EKcdDrE8pZ9M3nkeHuvYSySQ"}

r = requests.get(url, headers=headers)
print(r.status_code)
print(r.content)`

Can you please confirm that i should be using "http://192.168.0.107:42010/api/s/listenbrainz/1" as the URL?  I have tried many variants of that (http://192.168.0.107:42010/apis/listenbrainz/1, http://192.168.0.107:42010/api/s/listenbrainz/, http://192.168.0.107:42010/apis/listenbrainz/1, etc) and they all seem to result in the same behavior as each other.

**Comment by krateng** [comment]
The URL for Pano scrobbler should be http://192.168.0.107:42010/apis/listenbrainz. Are you using the latest Pano version and are you sure your mobile client is on the same network and can reach the Maloja server (try checking the web interface on your mobile browser)?

**Comment by jbmfg** [comment]
Thanks for the quick response.  Yep, i have access to the webui at 192.168.0.107:42010 on my mobile.  I think im using the latest pano, its the one i got from the play store, i cant find the version number though.  On simple scrobbler, it seems to crash simple scrobbler when i have the server in there.  In Pano the verify just immediately shows a red circle with cross trhough ti.

**Comment by jbmfg** [comment]
Just to be sure i was on the latest, i just installed the apk from the Pano github site.  Same problem though.

**Comment by krateng** [comment]
Could you run Maloja in the foreground (`maloja run`), then attempt verifying with Pano again and checking if the Maloja output says anything?

**Comment by jbmfg** [comment]
Doesnt register anything with Pano.  When i run the python script i mentioned in the OP i see "[apis] API request: ['validate-token']". 

So it would seem that the request from pano isnt getting to the maloja server.  I dont know why that would be, but i guess its not really a maloja problem.  But if you have an idea let me know!

**Comment by jbmfg** [comment]
Just to close the loop here, HTTP (cleartext) is not allowed in Pano.

**Comment by krateng** [comment]
Ah, I wasn't aware. Thanks for following up!
