### ISSUE TITLE
Secrets from files

### ISSUE THREAD

**Issue by Sohalt** [krateng/maloja#101]
It would be good to be able to specify the secrets (i.e. api keys) as files, e.g. `lastfm_api_secret=/path/to/file/containing/secret`.
That way it could be used e.g. with docker secrets and on NixOS.

**Comment by krateng** [comment]
The settings, including api keys, are currently stored in `/etc/maloja/settings.ini`. Can this file not already be mounted via Docker Secrets?

**Comment by Sohalt** [comment]
It can, though it makes the additional configuration live with the secrets. Ideally I want to be able to have everything except the secrets in git version control ("configuration as code") and only the secrets are mounted in at runtime.

**Comment by krateng** [comment]
Alright, this should now be possible if you manually upgrade your doreah installation to 1.7.3 and mount the files with the exact names of the setting in `/run/secrets`, so e.g. `/run/secrets/lastfm_api_key`. Full support will be in the next Maloja version.

**Comment by Sohalt** [comment]
Thank you!
