### ISSUE TITLE
[Question] Is there a way to mirror my Last.fm scrobbles?

### ISSUE THREAD

**Issue by carharv** [krateng/maloja#102]
I use an IOS app called Trax Scrobbler. It's really great because it detects and scrobbles audio to Last.fm playing from any source on my device. I have a lot of local files on my Spotify, so this is a key feature for me. 

Is there a way for me to essentially just have Maloja mirror all of the scrobbles on my Last.fm account? Thanks

**Comment by krateng** [comment]
Not natively at the moment, but if you don't mind installing another application, you might want to check out [multi-scrobbler](https://github.com/FoxxMD/multi-scrobbler) - I think it can do exactly that.

**Comment by FoxxMD** [comment]
Yes multi-scrobbler can do this for you! Check out the [last.fm instructions](https://github.com/FoxxMD/multi-scrobbler/blob/master/docs/configuration.md#lastfm-source) in the docs for setup.
