### ISSUE TITLE
Issues Importing History CSV

### ISSUE THREAD

**Issue by carharv** [krateng/maloja#104]
I requested my full listening history from Spotify and just finished a python script to convert it into the same CSV format that Maloja uses to import LastFM history. There are nearly 58k songs in my file, but there was a few thousand that Maloja didn't import. I originally thought it was an issue with unicode characters, but after fixing some I still got the same few thousand songs giving an error. 

<img width="1440" alt="malojaImportError" src="https://user-images.githubusercontent.com/61243088/160214497-27340d7a-c0f5-4bbe-82ba-386fce43d4d8.png">

Any ideas on how to fix these entries and get Maloja to accept them? Thanks

**Comment by krateng** [comment]
Looks like they all have commas in the title / album / artist, which clashes with the comma being used as a separator. IIRC the last.fm converter actually removes commas completely, so the quick way to fix this would be to remove all commas from your values and then import them as is, potentially fixing them afterwards in Maloja again.

What format does Spotify export your history as? Maybe I can add an import directly from that.

**Comment by carharv** [comment]
Ah ok that makes sense. Spotify sends listening history in the form of multiple JSON files. Here is a screenshot of a couple of my entries.
<img width="1029" alt="Screen Shot 2022-03-26 at 4 03 47 PM" src="https://user-images.githubusercontent.com/61243088/160255395-f18d0042-d9f8-46b2-9bdf-ef628e348c96.png">

It also seems like some of the songs weren't imported were replaced with a few thousand entries for "none - none" on the dashboard. 
<img width="1440" alt="Screen Shot 2022-03-26 at 4 07 33 PM" src="https://user-images.githubusercontent.com/61243088/160255488-e4e6d9e7-59d8-493c-92ea-8ec33dcef747.png">

**Comment by krateng** [comment]
Is the JSON file just an array at the outer level or does it begin with `{'data':` or something?

**Comment by krateng** [comment]
If you're building Maloja from source, you should now be able to run the `import` command with each Spotify export file. Otherwise let me know, I'll push a new version.

**Comment by carharv** [comment]
Yes the JSON file is just an array at the outer level. Thank you for adding support for this! I just rebuilt Maloja from source and tried `maloja import endsong_0.json` and it didn't work sadly. 
<img width="1039" alt="Screen Shot 2022-03-28 at 4 28 37 PM" src="https://user-images.githubusercontent.com/61243088/160482122-0f2aa5d0-8f23-415f-bc22-5fa3f33895d3.png">

**Comment by krateng** [comment]
Was there an output line right at the start `Parsing endsong_0.json as ...`? And can you try `maloja -V` just to make sure it's actually using your newly built version?

**Comment by carharv** [comment]
Version is 2.14.6. Git pull says it is up to date and I ran `pip install .` again, but I might not be doing something right. 

This is how it starts out 
`maloja import spotifyJSON/endsong_0.json`
`Already imported Last.FM data. Overwrite? [y/N]`
`y`
`Please wait...`
`Line '[' does not look like a valid entry. Scrobble not imported.`
`Line '  {' does not look like a valid entry. Scrobble not imported.`
`Line '    "ts": "2020-03-02T16:36:41Z",' does not look like a valid entry. Scrobble not imported.`

**Comment by krateng** [comment]
Oh wait I'm dumb, the new commit obviously wouldn't even show a different version 🤦 I'll just push a new tag, then you can update your Maloja the normal way from pypi or dockerhub and it should hopefully work.

**Comment by carharv** [comment]
I think this is an issue on my end, but I built it from source originally. I used git pull to get the new version, it says it's up to date, and then I do `pip install .` and it says malojaserver-2.14.7 has been successfully installed. 

However when I use `maloja start` and check the version it is running 2.14.6. Am I doing something wrong in the update process or is there a recommended way to uninstall so I can start fresh with the new version?

**Comment by carharv** [comment]
<img width="1440" alt="Screen Shot 2022-03-29 at 11 00 56 AM" src="https://user-images.githubusercontent.com/61243088/160642383-042dd6e5-1411-4bd5-87c5-9efe3ed9b167.png">
The Spotify import function does however seem to be recognized, albeit throwing errors.

**Comment by krateng** [comment]
Okay, another oversight on my part, the console output actually shows the version from a different source. Sorry for this, I shouldn't code tired :D

Looks like the error happens when the parsed scrobble has `None` as the artist and title. Don't know what Spotify means by that, but I assume that scrobble can just be skipped then?

**Comment by krateng** [comment]
Alright, new version should now handle those cases as well. I think you need to `pip uninstall maloja` first, then do a new `pip install .` in order to install the latest version.

**Comment by carharv** [comment]
I just tried it out with one of the JSON files and it imported them all! It also seemed to have added about 10k songs starting in the 1970's though... not sure where these came from.
<img width="1440" alt="Screen Shot 2022-03-29 at 11 46 07 AM" src="https://user-images.githubusercontent.com/61243088/160652488-5d4b7b60-684a-4981-9683-68c87725e0e2.png">

**Comment by krateng** [comment]
Wtf, those are from my test script to randomly generate songs. 

You should just be able to delete the file `randomgenerated.tsv` in your scrobble folder to get rid of them, but I'm really curious of how they got there. Did you run `maloja generate` at some point?

**Comment by carharv** [comment]
Ah yep I did while messing around trying to update it earlier. 

One last issue I'm running into is that I'm not able to import more than one JSON file without it overwriting the previous. 
After calling the import function again it says `Already imported data. Overwrite? [y/N]` and if I say `y` then it overwrites and if I say `n` then it gives an error and doesn't do anything.

**Comment by krateng** [comment]
Oh right, forgot there are multiple files. Should now also be fixed!

**Comment by carharv** [comment]
Awesome, thanks! I was able to get them all imported. It seems like there was some overlap in the Spotify files though so there are some duplicates. Would I be able to use the rules functionality to removed these duplicates or is there another way to go about it?

**Comment by krateng** [comment]
If Spotify actually exports duplicates, then I'd like handling that in the import function as well. Do they have the exact same ts in the original json file?

**Comment by carharv** [comment]
Yes, so it seems like the data is messier than I thought. All of these examples are on different lines. Some of them are in entirely different files. 

In this first example there are two different songs with different ms_played, but with the same time stamp. 
<img width="1650" alt="OT1" src="https://user-images.githubusercontent.com/61243088/160697669-09cb12f7-0149-49df-a700-b1135420be91.png">

In this second example these are the same song but with time stamps differing by one second.
<img width="1322" alt="RS1" src="https://user-images.githubusercontent.com/61243088/160697740-8f631056-3cfc-4615-8693-27b40d48b048.png">

In this third example there are two entries with the same song with the same ms_played but 21 seconds apart, and a third some with different ms_played that is only 4 seconds apart from the first entry. 
<img width="2000" alt="HH1" src="https://user-images.githubusercontent.com/61243088/160697774-176a9069-dbaa-4923-8ce4-df532f9c2480.png">

**Comment by krateng** [comment]
Hm, could the `ts` value just mean the time the information was registered server-side? The `offline_timestamp` field seems to be more reasonable from these examples.

**Comment by carharv** [comment]
According to the documentation from Spotify: 

|Field|Description|
| --- |       --- |
|ts|This field is a timestamp indicating when the track stopped playing in UTC (Coordinated Universal Time). The order is year, month and day followed by a timestamp in military time|
|offline_timestamp| This field is a timestamp of when offline mode was used, if used.|

The _offline_timestamp_ is the same for both entries of Heaven and Hell that are 21 seconds apart, but the _offline_timestamp_ is different for Bury Me Alive and Miracle Man even though the _ts_ is the exact same for each. Doesn't seem like there is any rhyme or reason to it.

**Comment by krateng** [comment]
Can you check for a few consecutive listens whether the offline_timestamp values are roughly apart as many seconds as the ms_played of the first listen indicates?

**Comment by krateng** [comment]
I've changed it up again now to look at all the files in the folder at once (to discard duplicates) and use the offline_timestamp. Let me know if that leads to more reasonable results. (Make sure to select [O]verwrite in the prompt)

**Comment by carharv** [comment]
That seems to have broken something. I called the import function with just one JSON file and it asked if I wanted to import the other 4 files too. I chose the overwrite option and it said it successfully imported 45,514 scrobbles. 

After rebooting the VM I loaded the web dashboard and it is only listing 4,807 scrobbles that are basically all dated December 31, 1969 between 7 and 8 pm

**Comment by krateng** [comment]
Oh, didn't even notice that timestamp had too many digits, it's in milliseconds :D I'll fix it.

**Comment by carharv** [comment]
Still about 150 scrobbles ended up in 1969 between 7 and 8 pm. All of the other scrobbles are showing up now and it looks much better!

**Comment by krateng** [comment]
Sounds good! Any chance you can find the equivalents of some of those 150 scrobbles in the original JSON file and post those entries?

**Comment by carharv** [comment]
It's actually 4,429 scrobbles in 1969, I was mistakenly looking at only one artist. Here are a few examples and they all have offline_timestamp as 0, which might be the issue. 

<img width="655" alt="Screen Shot 2022-03-31 at 1 33 39 PM" src="https://user-images.githubusercontent.com/61243088/161116449-b4044f8f-5d29-4dd6-a45c-492d4e798491.png">
<img width="799" alt="Screen Shot 2022-03-31 at 1 34 28 PM" src="https://user-images.githubusercontent.com/61243088/161116462-0b9f9503-ddaf-4685-8a20-765c24b097ba.png">
<img width="685" alt="Screen Shot 2022-03-31 at 1 35 54 PM" src="https://user-images.githubusercontent.com/61243088/161116472-01650744-99c4-4968-93b2-6d0b850e7928.png">
<img width="685" alt="Screen Shot 2022-03-31 at 1 36 28 PM" src="https://user-images.githubusercontent.com/61243088/161116477-79cbf93b-b97c-47fd-a2e9-63ee0fb9c94c.png">
<img width="685" alt="Screen Shot 2022-03-31 at 1 35 13 PM" src="https://user-images.githubusercontent.com/61243088/161116483-2aa79f07-ae52-4bb4-bab5-54f4e27fccb9.png">
<img width="685" alt="Screen Shot 2022-03-31 at 1 36 55 PM" src="https://user-images.githubusercontent.com/61243088/161116486-7c18c43e-3b46-4e0d-957e-585a513972d2.png">
<img width="685" alt="Screen Shot 2022-03-31 at 1 37 25 PM" src="https://user-images.githubusercontent.com/61243088/161116493-34269fab-4a0a-488e-aff7-7920d6e1ca7d.png">

**Comment by krateng** [comment]
Ah Spotify, fix your export logic :D

So my best idea for that would be to use the `ts` field as a fallback if `offline_timestamp` is 0. That would of course again lead to some duplicates with a few seconds difference and all that, but at least now only for a small subset of all scrobbles.

**Comment by carharv** [comment]
Yeah that sounds like a good way to get most of the duplicates out. This is a more complicated solution, but would you be able to use the ms_played as a reference to check for duplicates? If ms_played is bigger than the difference in time stamps, then it would be a duplicate, right?

I'm working on an email to Spotify, but I am doubtful they will have any insight for me.

**Comment by krateng** [comment]
The scrobbles aren't in order though, right? This would mean when checking each scrobble it would have to be compared to every other scrobble in all the files.

**Comment by krateng** [comment]
Alright I reworked the whole thing a bit so there might again be new and exciting bugs 😅

I added the option to only import one file so you can test it with a small file first to save time; if that leads to reasonable results, you can try again with all files.

**Comment by carharv** [comment]
Yep that seems to have cleaned things up quite a bit! No more scrobbles in the 1900s and I didn't see any duplicates on a quick glance. I plan on going through the Spotify files manually and cleaning things up a bit eventually, so I will let you know how accurate your import method is. Thanks again!

**Comment by krateng** [comment]
Closing this for now as import is implemented, but if you end up finding issues in the dataset, feel free to reopen!
