### ISSUE TITLE
exception from database in v3.0.0

### ISSUE THREAD

**Issue by bayang** [krateng/maloja#106]
Hi just tried latest 3.0.0 merged into master via docker-compose

Ran docker-compose up after pulling latest from docker-hub and had this stacktrace in the logs : 

```shell
Attaching to maloja
maloja              | 2022-04-12T15:12:41.737050445Z Exception in thread Thread-11:
maloja              | 2022-04-12T15:12:41.737136738Z Traceback (most recent call last):
maloja              | 2022-04-12T15:12:41.737152241Z   File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
maloja              | 2022-04-12T15:12:41.737165178Z     self.run()
maloja              | 2022-04-12T15:12:41.737177388Z   File "/usr/lib/python3.9/threading.py", line 910, in run
maloja              | 2022-04-12T15:12:41.737189777Z     self._target(*self._args, **self._kwargs)
maloja              | 2022-04-12T15:12:41.737204110Z   File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 386, in start_db
maloja              | 2022-04-12T15:12:41.737216920Z     upgrade.upgrade_db(sqldb.add_scrobbles)
maloja              | 2022-04-12T15:12:41.737227897Z   File "/usr/lib/python3.9/site-packages/maloja/upgrade.py", line 70, in upgrade_db
maloja              | 2022-04-12T15:12:41.737239263Z     timestamp, artists, title, album, duration = scrobble
maloja              | 2022-04-12T15:12:41.737250269Z ValueError: not enough values to unpack (expected 5, got 4)
```
The UI is accessible but displays an error message

```
You are only seeing this information because you are in admin mode:

No Traceback
```

**Comment by mannp** [comment]
Same issue for me.

**Comment by krateng** [comment]
Ah right, old scrobbles didn't have those extra columns. Should be fixed with latest commit!

**Comment by mannp** [comment]
Mmh, so updated to 3.0.1 and for me, I am getting a 503 still after about 5 mins and nothing in the log.

I am able to access the new admin panel 👍🏻 which shows I am on v3.0.1 but still 503 on the main page.

**Comment by krateng** [comment]
How many scrobbles do you have? The upgrade is quite slow, could easily take 20 minutes or longer on an average CPU. If 'malojadb.sqlite' in your data folder is being modified / getting bigger, it should be fine.

**Comment by mannp** [comment]
```
2022/04/12 16:13:33  Upgrading v2 Database to v3 Database. This could take a while...
2022/04/12 16:13:33     Importing from lastfmimport.tsv (1/20) - 27463 Scrobbles
```

malojadb.sqlite is being updated yes 👍🏻  will wait :)

**Comment by bayang** [comment]
Ok it seems fine for me too now, the database size is growing despite having no logs to follow progression or whatsoever.

Just one question, the scrobbling clients credentials are still stored in /clients/authenticated_machines.tsv ? 
Or do I have to set up again everything ?

**Comment by krateng** [comment]
The credentials are now stored in `/apikeys.yml`, but they should be automatically transferred.
