### ISSUE TITLE
v3 migration included last.fm import data even though existing db did not include

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#107]
```
2022/04/12 16:13:33  Upgrading v2 Database to v3 Database. This could take a while...
2022/04/12 16:13:33     Importing from lastfmimport.tsv (1/20) - 27463 Scrobbles
```

I initially imported my last.fm history into Maloja some time ago, so had the last.fm data in the Maloja data directory.

The note is that my 'current' db did not include those past scrobbles, but they are being merged with the v3 migration?

I elected to start a fresh (mainly due to not being able to easily delete on mass previous scrobbles from Maloja)

I just wondered if the import of the last.fm csv data on migration was by design?

Cheers.

**Comment by krateng** [comment]
What do you mean that your current db did not include it? If the `lastfmimport.tsv` file was in your scrobble folder, it should always have been included in your database.

**Comment by mannp** [comment]
> 

Yes, current v2 db did not include previous last.fm data.

I had initially imported it, then deleted the other config files and started again.

The csv was there, but not imported.

I have backups, but wondered why the csv was being merged when it was not part of the migrating v2 db.

**Comment by krateng** [comment]
The csv isn't being merged, just the tsv that should be the result of the initial import. If the migration sees a tsv file, it must be there. Do you maybe have an old and a new data directory, one of them including the `lastfmimport.tsv`?

**Comment by mannp** [comment]
Interesting, I have a lastfmimport.tsv in my scrobbles, so I am not clear, but as they are there, it would be expected maloja would migrate them.

Perhaps my memory is failing, but I was sure I had imported, deleted and started again :)

I flagged in case of an issue for others, but perhaps it's no issue at all :)

**Comment by krateng** [comment]
So all good then?

If you want to redo the import, your old scrobble files should be in the `.oldscrobbles` folder, you can move them over again to `scrobbles` (and delete `lastfmimport.tsv`), then start the server again.

**Comment by mannp** [comment]
> 

I have backups, so was all good, just wasn't clear on what was actually getting migrated.

I am still waiting for the migration to complete, so will see what I end up with, else I will do as you say and restart 👍🏻
