### ISSUE TITLE
Docker env PW not accepted

### ISSUE THREAD

**Issue by iophobia** [krateng/maloja#109]
Hi, just gave your container a spin on my Synology. Passed the `MALOJA_FORCE_PASSWORD` as an env variable to the container but am now perplexed why it prompts with challenge/PW/response when trying to access the admin/settings site. Is it supposed to be entered as a hash in the env field or what am I missing?

Thanks in advance.

**Comment by krateng** [comment]
Just enter the password in the password field and it should work. The other fields are just in case you use any browser extension and don't want to trust the website with your password.
