### ISSUE TITLE
Local images not showing up

### ISSUE THREAD

**Issue by UntilItsGone** [krateng/maloja#11]
Hi. I've been trying to get Maloja to show local images in every way I could think of but it doesn't seem to want to work.

### Things I tried:
(Let's pretend my top artist is called Band Name and my top track is called Song Title)
- Putting BandName.jpg in ~/.local/share/maloja/images
- Putting bandname.jpg in ~/.local/share/maloja/images
- Making a folder called BandName in ~/.local/share/maloja/images and putting the picture inside it.
- Making a folder called bandname in ~/.local/share/maloja/images and putting the picture inside it.
- Doing the same thing with a png file instead of a jpg one.
- Doing the same thing with BandName_SongTitle.jpg, bandname_songtitle.jpg, BandName_SongTitle.png and bandname_songtitle.png
- Doing the same thing with a different band/different song.
- Enabling admin mode then dragging and dropping pictures on the artist/song tiles (no matter where I drop a picture the browser just opens it instead of adding it to the page.)

Now I'm at my wits' end. Either there's something really obvious that I'm completely overlooking or I'm doing things right and it's just a weird bug.
I did try shutting down and restarting the server in between each change to the images folder and I did try deleting the cache.
I did add `USE_LOCAL_IMAGES = true` and `CHARTS_DISPLAY_TILES = true` to my settings.ini file.
I am running the latest version of Maloja.

I'd rather handle everything locally so I haven't tried adding a last.fm/spotify/fanart.tv API yet and I'd rather avoid doing so, but I guess I could try if it's the absolute last resort. Thanks in advance.

**Comment by krateng** [comment]
Sorry, it seems I completely missed mentioning that in the .info file - you need to have a subfolder `artists` or `tracks` in the `images` folder. Then copy the files into that and they should show up (after a server restart).

**Comment by UntilItsGone** [comment]
Yup, that completely fixed the problem. Thank you!
