### ISSUE TITLE
start script returns error code

### ISSUE THREAD

**Issue by da2x** [krateng/maloja#113]
https://github.com/krateng/maloja/blob/4a8221f7a08f679b21c1fb619f03e5f922a1dc2b/pyproject.toml#L43

generates a binary which calls

```
   sys.exit(main())
```

https://github.com/krateng/maloja/blob/72941558d2fa0950d782d0cd2c0bfe2d5797a93f/maloja/__main__.py#L4
https://github.com/krateng/maloja/blob/741246a7c160dd68a810ab50bebf2de380c6110a/maloja/proccontrol/control.py#L141

That last `True` gets interpreted as 1 causing the control process to exit with status 1; which indicates the program exited with an error state. It should return 0 on success.

**Comment by krateng** [comment]
Should be fixed in next version!
