### ISSUE TITLE
api explorer no longer provides response details

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#114]
The endpoint response details in api explorer later than 3.0.0 [do not display any information.](https://user-images.githubusercontent.com/4663766/163398538-86746259-489e-4bea-a56c-870bdcb5d565.png)

**Comment by FoxxMD** [comment]
Off topic...what is the difference between `duration` and `length` in the scrobble object?

![image](https://user-images.githubusercontent.com/4663766/163399755-6a9f7fc5-d32b-4e5b-9297-f73415f86597.png)

**Comment by FoxxMD** [comment]
Oops sorry i deleted the duration/length comment because i found it in the repo, just before you responded :)

> did that actually ever show descriptions?

You know...im not sure. But I do vaguely remember relying on it. 

If you don't want to fully fix/rework the api explorer then a quick markdown document in the repo detailing some of the most used resources would be helpful:

* shape of scrobble data (response)
* shape of scrobbles in list (response)
* shape of data for new scrobble (request) and content-type

**Comment by krateng** [comment]
I can add the descriptions to the explorer, no worries, I was just confused because I tried to find the commit where I must have removed them and apparently they were never there :D

**Comment by krateng** [comment]
Alright, there should now be some basic info - it's not extensive in regards to the return data structures yet, but I'll work some more on that in the future. Nimrodel probably needs a major overhaul at this point as well to make this a bit more elegant.
