### ISSUE TITLE
API key and password to admin is printed after container shutdown

### ISSUE THREAD

**Issue by northys** [krateng/maloja#117]
What happened: After I've run maloja in docker using official image provided I wondered where should I get admin password and API key. Maloja printed that information suddently after I pressed CTRL-C to stop it.

What I expected: I would expect that those information would be provided immediately printed to stdout. Re-running the same container on same data directory prints logs immediately with no problem. Only the first init run behaves like this.

```
docker run -p 42010:42010 -v $PWD:/mljdata -e MALOJA_DATA_DIRECTORY=/mljdata krateng/maloja
^C // stop by ctrl-c prints the info
Maloja v3.0.4
https://github.com/krateng/maloja

Various external services can be used to display images. If not enough of them are set up, only local images will be used.
Your API Key: secret
Generated password: secret
[server] Starting up Maloja server...
[server] Listening on 0.0.0.0:42010
[dbcache] Cache Size: 1 [0 E], System RAM Utilization: 57.3%, Cache Hits: 0/1
[sqldb] Database Cleanup...
[sqldb] Database Cleanup complete!
[dbcache] Cache Size: 1 [0 E], System RAM Utilization: 61.4%, Cache Hits: 0/1
[sqldb] Database Cleanup...
[sqldb] Database Cleanup complete!
```

**Comment by krateng** [comment]
I've encountered this as well, but have no idea why it happens. Running it directly prints the output immediately, but somehow Docker doesn't want to forward it. I'll investigate!

**Comment by FoxxMD** [comment]
The fact that it doesn't appear until shutdown sounds like maloja (or the OS?) is buffering output to stdout/stderr and then dumps it when a process is killed. I don't know why it would only do this first-time though...maybe its because log files haven't been created yet?

**Comment by northys** [comment]
the question is simple. how does maloja handle logs? is there some kind of library with adapters for stdout/file/anything? or do you just use some python native print to stdout/stderr? there is no reason why would docker/system buffer it.

when you create alpine image with encrypoint echoing "hey i'm alive" you see it immediately. same when you echo in php. i'm not familiar with python ecosystem though.

**Comment by krateng** [comment]
Maloja does have its log system, but these messages at the start aren't actually handled by it - they are just printed to stdout with Python's native `print()`.

**Comment by northys** [comment]
confirmed
```
northys at northys-fedora in /t/maloja (master|✔)
» docker build -f Containerfile -t maloja .
northys at northys-fedora in /t/maloja (master|✔)
» docker run maloja:latest 

Maloja v3.0.5
https://github.com/krateng/maloja

Various external services can be used to display images. If not enough of them are set up, only local images will be used.
Your API Key: Z5ycoDKFhrJiZQ3GDZ42YUiCWgRlzcxEA0RbE3OcDwh7DJ9a0L6DPkP2dWOKsl5f
Generated password: 9uBidXvDUvYl74LhRN3QVPbf2fzbd87b
[server] Starting up Maloja server...
[server] Listening on *:42010
[dbcache] Cache Size: 1 [0 E], System RAM Utilization: 50.6%, Cache Hits: 0/1
[sqldb] Database Cleanup...
[sqldb] Database Cleanup complete!
```
