### ISSUE TITLE
Parse artist featured in square brackets "[feat. <artist>]"

### ISSUE THREAD

**Issue by alim4r** [krateng/maloja#121]
Amazon Music uses `[feat. <artist>]` for their artists.

### Example 
```python
>>> cla.fullclean("Raaban & Tungevaag [feat. A7S]", "Try Again (feat. A7S)")
(['A7S', 'Raaban', 'Tungevaag [feat. A7S]'], 'Try Again')
```
This parses `Tungevaag [feat. A7S]` instead of only `Tungevaag`.

Round brackets do work:
```python
>>> cla.fullclean("Raaban & Tungevaag (feat. A7S)", "Try Again (feat. A7S)")
(['A7S', 'Raaban', 'Tungevaag'], 'Try Again')
```

### Proposed change
https://github.com/krateng/maloja/blob/fe21894c5ecf3a53c9c5c00453abfc7f41c6a83e/maloja/cleanup.py#L111-L114

Changing the regex expression to `r"(.*) [\(\[]" + d + " (.*)[\)\]]"` will also match square brackets:

```python
cla.fullclean("Raaban & Tungevaag [feat. A7S]", "Try Again (feat. A7S)")
(['A7S', 'Raaban', 'Tungevaag'], 'Try Again')
```

but this will also match mismatched bracket types like `[feat. A7S)` or `(feat. A7S]`.

**Comment by krateng** [comment]
Huh, I actually had handling for that in the title but not the artist. Good catch, I'll fix it!

**Comment by alim4r** [comment]
Thanks! :)

**Comment by alim4r** [comment]
Works with the new commit!

**Comment by alim4r** [comment]
@krateng I noticed that you also removed replacing square brackets into round brackets for the title.
https://github.com/krateng/maloja/blob/17be00f7945d0078988a79a178546f6c4023a7ea/maloja/cleanup.py#L142

Is this intended? Now there will be two entries for songs with `[Explicit]` in the title.
#### Example
new: `t r a n s p a r e n t s o u l [Explicit]` 
old: `t r a n s p a r e n t s o u l (Explicit)`

**Comment by krateng** [comment]
This was intended as it was originally just a cheap workaround to get the later regexes working for both brackets - but now that you mention it, it's probably a good idea anyway because I doubt there's many artists who have made two songs that are named exactly the same only with different brackets.

**Comment by alim4r** [comment]
ok, thanks. Just wanted to make sure before trying to fix the old tracks.


Maybe someone finds it helpful how changed  `[Explicit]` back to `(Explicit)`.
Check before if tracks with both versions exist:
```sql
SELECT t.title, t.id FROM tracks as t WHERE t.title LIKE "%explicit%" ORDER BY t.title;
```
and update those scrobbles by hand to the correct version.

Change `[Explicit]` to `(Explicit)`
```sql
UPDATE tracks SET title = REPLACE(title,'[Explicit]','(Explicit)'), title_normalized = REPLACE(title_normalized,'[explicit]','(explicit)');
```
