### ISSUE TITLE
Edit past scrobbles or Rebuild database against current rulesets?

### ISSUE THREAD

**Issue by lylebrown** [krateng/maloja#123]
Hello,

I have been recording scrobbles with maloja for about a day now and have set up a couple rules to fix some incorrect parsing, and I have confirmed they work for new scrobbles.

However, I would like to apply these to the old scrobbles as well. Is there a way I can rebuild the database against these new rulesets? Or even just manually edit past scrobbles?

**Comment by krateng** [comment]
You will be able to manually edit track titles and artist names in version 3.1 (see the [feature-webedit](https://github.com/krateng/maloja/tree/feature-webedit) branch), and reparsing is currently in the works in #122! Can't give you an exact ETA but hopefully very soon™. For now, it's possible to make the edits in the file `malojadb.sqlite` if you're familiar with SQL.
