### ISSUE TITLE
Is there some sort of cache?

### ISSUE THREAD

**Issue by northys** [krateng/maloja#125]
After import of my 280k records from last.fm export I still see no data in the UI. They appear after maloja container restart. Is it possible to clean the "cache" somehow?

**Comment by krateng** [comment]
The import isn't really meant to be done while the main server is running. The cache is process-specific, so the server doesn't know that you're editing the database from somewhere else; but you could force at least a partial cache refresh by submitting a new scrobble.

**Comment by northys** [comment]
I understand. I use dockerized version so the web process is always running because I exec to it and do not change the entrypoint / command.

What is the point of using the cache btw? Did you experience some performance issues with sqlite without caching? I would expect that the sqlite file (which is about 20-30MB) can fill into system file cache entirely and SQL selects should be blazingly fast because it doesn't have to touch the disk at all.

**Comment by krateng** [comment]
I had some performance issues without the cache, not in terms of disk read times but the CPU for more complicated stats. It varied a lot though and I still haven't settled on an exact configuration - you can try disabling the cache in your settings (`USE_GLOBAL_CACHE`).
