### ISSUE TITLE
Docker memory usage query.

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#128]
```
NAME    CID          CPU MEM    NET RX/TX          IO R/W           PIDS
maloja  9c0b61db6c99 0%  731M / 15.50G  5M / 242M  60M / 0B         22
```

I was just reviewing my docker server usage and was surprised by the amount of memory use by Maloja while idling :-/

Currently, using v3, but didn't check what v2 was using.

I am reading this correctly, as it seems rather high...according to ctop at least.

**Comment by krateng** [comment]
Maloja will happily use all memory available for caching, as unused memory is wasted memory. It should release it though when it's needed - you can adjust the threshold in the settings (RAM percentage soft limit) or completely disable the cache (Use global DB cache).

**Comment by mannp** [comment]
So these are my default settings after my v2 upgrade... not entirely clear how they interact, as you mentioned 'Use global DB cache' should disable the cache, therefore my 731M memory usage wouldn't be cache then would it, as it's ticked?

```
RAM Percentage soft limit 80%
Use request-local DB Cache - ticked  
Use global DB Cache - ticked
```

**Comment by krateng** [comment]
No I just meant that's the option name - Ticking `Use global DB Cache` means you use the cache, unticking it means disabling it. If you disable it and then restart, there should be no memory use from cache.
