### ISSUE TITLE
Improve unicode handling on CSV import

### ISSUE THREAD

**Issue by idanoo** [krateng/maloja#13]
Trying to import my last.fm list is getting the following error:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4256`
This is the result of the artist `Jack Ü`

https://stackoverflow.com/questions/23396069/best-way-to-convert-unicode-in-csv-to-plain-text

The following file can be used as an example to break it.
[tmp.txt](https://github.com/krateng/maloja/files/4453233/tmp.txt)

Edit:
The follow apostrophes appear to break it too.
`Vigiland,We’re The Same,We’re The Same,07 Apr 2020 23:24`

**Comment by idanoo** [comment]
The following file can be used as an example to break it.
[tmp.txt](https://github.com/krateng/maloja/files/4453233/tmp.txt)

**Comment by krateng** [comment]
That file seems to work for me. Are you sure you're using Python 3?

**Comment by idanoo** [comment]
Thanks - Seems to have been my locale was not set correctly (Was running in a container)
