### ISSUE TITLE
[Feature Request] Placeholders for empty results

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#134]
The `This Week` and `Today` tabs on Top Tracks do not show anything. Which is correct since it's a monday and i haven't scrobbled anything today! 

![image](https://user-images.githubusercontent.com/4663766/165116311-86bfe42d-d82d-4d41-8966-afdefcf2502d.png)

However it isn't apparent that this is the case from the ui since it's just blank. For these types of views could you return a "nothing scrobbled yet!" placeholder, or something similar?

**Comment by krateng** [comment]
Hm, I can't find a free tumbleweed svg... I'll see what I can come up with.

**Comment by krateng** [comment]
![image](https://user-images.githubusercontent.com/15263881/165122797-8b17238c-9f75-4118-ad50-008df07f73bf.png)

Would this work?

**Comment by FoxxMD** [comment]
thats perfect, thanks
