### ISSUE TITLE
Track editing does not work

### ISSUE THREAD

**Issue by lylebrown** [krateng/maloja#140]
Just updated to the latest version of Maloja and I'm running into an issue when clicking the edit button on a track.

Nothing visually happens, and I get the following error in the browser console:

`Uncaught ReferenceError: editEntity is not defined
    at HTMLDivElement.onclick `

Let me know if there's any other info I can provide.

**Comment by krateng** [comment]
Can you check if the javascript file is cached? Go to `yourinstance.tld/edit.js` and refresh it a few times, then try again.

**Comment by lylebrown** [comment]
I think that was the issue, thanks! The merging feature is honestly incredible, thanks for that! 😄
