### ISSUE TITLE
Error 400 with gonic server

### ISSUE THREAD

**Issue by tomatgithub0** [krateng/maloja#141]
Hi,

Appreciate the hard work.

My setup consists of a Maloja scrobbler and a gonic with ListenBrainz URL points to Maloja, however every time server tries to submit a song an error code of 400 returns, stating invalid json document.

Thanks

**Comment by tomatgithub0** [comment]
Sorry, my knowledge it very limited when it comes to networking, if there's more that I can help with I would definitely give it a go!

**Comment by krateng** [comment]
No worries - are you running from source, Dockerhub or PyPI?

**Comment by tomatgithub0** [comment]
Thanks, I'm running from dockerhub.

**Comment by krateng** [comment]
Alright, let me know if that fixed it!

**Comment by tomatgithub0** [comment]
Thank you very much! I'll have a test as soon as the docker build's updated

**Comment by sentriz** [comment]
hi! for gonic the :nightly image should already have the fix

**Comment by tomatgithub0** [comment]
Hi guys, just did a test with the latest docket build however scrobbling still doesn't work, no error messages from Maloja, gonic only reports something like missing song ids, not sure if it's related though.

Thanks!

**Comment by sentriz** [comment]
@tomatgithub0 what exactly is the message from gonic?

**Comment by tomatgithub0** [comment]
Every time I start playing a song:

gonic log shows: `subsonic error code 10: please provide an 'id' parameter`

Maloja log shows: `[apis] Listenbrainz API request: ['submit-listens']`

And couple of mins in, gonic log gives: `subsonic error code 70: view not found`

Thanks for looking into this!

**Comment by tomatgithub0** [comment]
Sorry, checked Maloja again after the last comment and the songs I played were logged!

Not sure why it took so long though. That was at least 10 mins apart.

**Comment by krateng** [comment]
The scrobble shows up in the web interface 10 minutes after the Maloja log shows the Listenbrainz request?

**Comment by tomatgithub0** [comment]
Well maybe not 10 mins since I wasn't paying attention. I figured it won't show up til the playback is complete so I guess thats the logic behind it. Nonetheless I can live with it.

Thanks again for all your guys' help!
