### ISSUE TITLE
Wrong artists when using /newscrobble

### ISSUE THREAD

**Issue by badlandspray** [krateng/maloja#144]
```
data = {
            "artists": ["Frank Sinatra"],
            "title": "Come Fly With Me",
            "album": "Come Fly With Me",
            "length": 227,
            "albumartists": ["Frank Sinatra", "Count Basie"],
            "time": 1651830072,
            "duration": 334,
            "key": "..."
}
r = requests.post("https://domain.tld/apis/mlj_1/newscrobble",data=data)
```
Logs:
`maloja  | [database] Incoming scrobble [Client: default | API: native/v1]: {'track_artists': ['F', 'r', 'a', 'n', 'k', ' ', 'S', 'i', 'n', 'a', 't', 'r', 'a'], 'track_title': 'Come Fly With Me', 'album_name': 'Come Fly With Me', 'album_artists': ['C', 'o', 'u', 'n', 't', ' ', 'B', 'a', 's', 'i', 'e'], 'scrobble_duration': 227, 'track_length': 227, 'scrobble_time': 1651830072}`

Artists being created for each letter. In case of multiple artists, only one artist is being considered.

**Comment by krateng** [comment]
`requests.post` creates a form data request - you need to use JSON.
