### ISSUE TITLE
Add a tag to dockerhub image

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#15]
To pull an image from [dockerhub](https://hub.docker.com/r/krateng/maloja/tags) a tag is required. Please tag the image build with `latest`! Thanks

**Comment by Rfvgyhn** [comment]
Manually tagging would be great. Even better would be to have dockerhub automatically build and tag the image for you. By [setting up automated builds](https://hub.docker.com/repository/docker/krateng/moloja/builds/edit), users can pull the latest whenever you commit/tag on github.

This is an example of one of my image's automated builds.
![Screenshot from 2020-05-03 00-31-58](https://user-images.githubusercontent.com/731861/80907598-a4430600-8cd5-11ea-8fd7-16e6aa625f04.png)

Which leads to [this list of tags](https://hub.docker.com/repository/docker/rfvgyhn/factorio/tags?page=1).

**Comment by FoxxMD** [comment]
If anyone wants to use maloja from dockerhub in the interim I've got the latest commit tagged here https://hub.docker.com/repository/docker/foxxmd/maloja

**Comment by krateng** [comment]
Hey, sorry for the delay. Sadly I couldn't get docker to work so far and I can't seem to just upload the Dockerfile manually, so if it's okay I'm just gonna refer to your file for now. I'll try again when I have some more time!

**Comment by Joniator** [comment]
If anyone is interested, I have set up an automatic build that pulls the latest version from pypi and packs it into a tagged docker image. https://hub.docker.com/r/joniator/maloja

Currently I use a slightly different Dockerfile from the repo, if something significantly changes (e.g. new dependencies, different command to start) the pipeline needs to be adjusted.

If nothing changes this should just chug along
