### ISSUE TITLE
Manual scrobbles not working

### ISSUE THREAD

**Issue by Mysgym** [krateng/maloja#160]
Just installed maloja with pip also tried docker which has the same issues, followed the quick configuration and tried adding a test manual scrobble.
The manual scrobble never shows up in the home page, tried connecting web scrobbler with both API but this gives the same result (no error on web scrobbler).

The logs aren´t showing any error, but they aren't showing anything relating to scrobbles either (don't know if they should)

Importing scrobbles from .csv works as intended though

**Comment by FoxxMD** [comment]
Have you turned logging on?

This can be done through the admin panel settings in the web interface or by setting `Logging = true` in your `settings.ini` file.

**Comment by Mysgym** [comment]
Logging is enabled
I'm not sure which log file I should be checking, but none of the files in the logs folder receive any event when I manual scrobble.

The logs are small so I'll paste them all here 

```
logs/server.log // same two lines each time I start, nothing else

2022/08/05 xx:xx:xx  Starting up Maloja server...
2022/08/05 xx:xx:xx  Listening on *:42010
```
```
logs/dbcache.log // same lines at regular intervals, nothing else
2022/08/05 xx:xx:xx  Cache: Size: 1 | Hits: 0/1 | Estimated Memory: 64 B
2022/08/05 xx:xx:xx  Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 36 B
2022/08/05 xx:xx:xx  System RAM Utilization: 27.8%
```
```
logs/debug_performance // logs on web page switch, nothing else

2022/08/05 xx:xx:xx Executed jinja_page (('<page name>',), {}) in 0.24s
```
```
logs/sqldb.log // same two lines at regular time intervals, nothing else

2022/08/05 xx:xx:xx  Database Cleanup...
2022/08/05 xx:xx:xx  Database Cleanup complete!
```

logs/.maloja_log_sentinel is empty and dbfix only has a dummy file empty as well.

And for sanity check, here is my settings.ini :
```
./settings.ini

[MALOJA]
lastfm_api_key = False
spotify_api_id = False
spotify_api_secret = False
audiodb_api_key = False
logging = True
```

**Comment by FoxxMD** [comment]
I'm not sure how to debug the manual scrobble but lets verify your server is reachable and maloja is responding correctly.

In your browser go to this URL, using the domain you are using with webscrobbler:

```
https://YOURDOMAIN/apis/mlj_1/test?key=YOURMALOJAKEY
```

You should receive `{"status": "ok"}` if the server is reachable and responding.

If you get a timeout or not found response then the server is not reachable from whatever domain you are trying to use.

Next, ensure a scrobble endpoint is working correctly.

This command can be run from the command line on linux/mac (replace values where needed):

```
curl --location --request POST 'https://YOURDOMAIN/apis/mlj_1/newscrobble' \
--header 'Content-Type: application/json' \
--data-raw '{
    "artists": ["Taiwa"],
    "title": "Mountains of Metal",
    "key": "YOURMALOJAKEY"
}'
```

Your should receive a json response with `"status": "success"` in it. You should also be able to see a new scrobble in the web interface.

If the auth test worked but this did not hopefully you should have some kind of error response.
___

If both of those work but webscrobbler still isn't working then likely you have the URL incorrect for the webscrobbler endpoint.

**Comment by Mysgym** [comment]
Server is reachable and adding scrobbles using the maloja API works fine. I've just tried a different scrobbler which gave me detailed errors with the listenbrainz api connection. It turns out Maloja's listenbrainz api url is ./apis/listenbrainz/1/ instead of ./apis/listenbrainz as hinted in the admin_setup page.

using this url, external scrobblers seem to work fine, manual scrobbles are still borked

**Comment by FoxxMD** [comment]
Glad to hear that part is resolved! Will probably need to wait for @krateng to chime in on the manual scrobble. Only thing I could suggest is open the [devtools](https://developer.chrome.com/docs/devtools/open/) **console** pane while on the manual scrobble page. Try to send manually scrobble and see if any errors show up in the console. Can also check the **network** page to see if any requests failed.

If anything errors/fails post it here.

**Comment by krateng** [comment]
I'd also like to see t he devtools console output. Also, make sure you actually confirm the artist input (it should become a separate element without underline).

**Comment by Mysgym** [comment]
I wasn't confirming the input... problem solved ! Thanks for the support
