### ISSUE TITLE
Can't update album art by drag-and-dropping

### ISSUE THREAD

**Issue by pncht** [krateng/maloja#161]
**Expected behavior**: drag and dropped album/artist art should replace currently empty album art
**Actual behavior**: drag-and-dropped album/artist art does not appear
**Steps to replicate**: (1) log into admin panel, (2) activate admin mode, (3) go to any artist or track page, (4) attempt to change image by drag and dropping.
This was tested on Firefox 103.0, and I am neither able to add new images nor replace existing ones.   Is it possible to upload images through the system file picker, or save them in some specific directory in the filesystem?  Thanks.
![vokoscreen-2022-08-08_05-37-29](https://user-images.githubusercontent.com/99764385/183388229-14004ae8-992c-4fa6-9148-da08281f0ffc.gif)

**Comment by krateng** [comment]
Could you open the dev console and see what it says when you're trying to upload?

Manually, you can place images in the data folder under `images/tracks` or `images/artists`, according to [these](https://github.com/krateng/maloja/blob/master/maloja/data_files/state/images/images.info) rules.

**Comment by domainzero** [comment]
Having this same issue. Here's the error I get in my console
```javascript
Uncaught TypeError: FileReader.readAsArrayBuffer: Argument 1 is not an object.
    readImageFile https://scrobble.hailsatan.xyz/neopolitan.js:30
    EventHandlerNonNull* https://scrobble.hailsatan.xyz/neopolitan.js:37
    EventListener.handleEvent* https://scrobble.hailsatan.xyz/neopolitan.js:37
[neopolitan.js:30:219](https://scrobble.hailsatan.xyz/neopolitan.js)
    readImageFile https://scrobble.hailsatan.xyz/neopolitan.js:30
    (Async: EventHandlerNonNull)
    <anonymous> https://scrobble.hailsatan.xyz/neopolitan.js:37
    (Async: EventListener.handleEvent)
    <anonymous> https://scrobble.hailsatan.xyz/neopolitan.js:37
```

**Comment by domainzero** [comment]
It looks like this might just happen if you try to drag an image from a browser (i.e. image open in another tab) vs. an image from the local filesystem.

**Comment by krateng** [comment]
Ah, I didn't actually specify that in the docs - yes, this only works for uploading from the filesystem.
