### ISSUE TITLE
Possible to import Listenbrainz json files?

### ISSUE THREAD

**Issue by krateng** [krateng/maloja#162]
### Discussed in https://github.com/krateng/maloja/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **1xPdd** July  9, 2022</sup>
I'm trying to import my Listenbrainz listen history, which exports as a JSON file. Maloja's import command simply says, "scrobbles.json could not be identified as a valid import source." Could anyone offer any suggestions how I might convert this file to something that Maloja can ingest?

edit: the export function can be found here https://listenbrainz.org/profile/export/</div>

**Comment by krateng** [comment]
@1xPdd I can add support for the format. Would you mind providing an example file?

**Comment by bbsixzz** [comment]
Maloja version: 3.1.4

I just exported my data from ListenBrainz and I get `File export.json could not be identified as a valid import source.`
