### ISSUE TITLE
Artist split into two when name contains "&"

### ISSUE THREAD

**Issue by juergenbr** [krateng/maloja#165]
**Description:**

If a song is scrobbled from an Artis that contains "&" in his name, Maloja thinks that it is two artists and scrobbles the same song for two different artist, one for the words before "&" and one after.

**How to reproduce the issue:**

- Artist name: Above&Beyond
- Track Name: Chains (ABGT497)
- Scrobbled song: Above, Beyond - Chains (ABGT497)

**Comment by FoxxMD** [comment]
[Solution here](https://github.com/krateng/maloja/issues/154)

**Comment by juergenbr** [comment]
Thanks! Apologies for overlooking this closed issue.
