### ISSUE TITLE
Jinja Template renders song title as html tag

### ISSUE THREAD

**Issue by alim4r** [krateng/maloja#167]
Songs with `<...>` in the title are rendered as html tag.

### Example
For example the song `<maybe> it's my fault` from WILLOW is shown as `it's my fault`.
The full title seems to be in the DB.
The site `/track?artist=WILLOW&title=<maybe>+it%27s+my+fault` also shows the full song title in the url and renders the title as:
```html
<h1 id="main_entity_name" class="headerwithextra">
	<maybe> it's my fault</maybe>
</h1>
```

The song `<Coping Mechanism>` from WILLOW displays no name at all and is rendered as:
`/track?artist=WILLOW&title=%3CCoping+Mechanism%3E`
```html
<h1 id="main_entity_name" class="headerwithextra">
	<coping mechanism=""></coping>
</h1>
```

The browser tab names are shown correctly
![image](https://user-images.githubusercontent.com/7687869/194536032-c01b8dc7-191b-41ce-bed5-3231dd606d8f.png)

**Comment by krateng** [comment]
Should now work correctly!

**Comment by alim4r** [comment]
Thanks! It works for the track title headline.

It seems like scrobble lists and the search results also have this issue.
