### ISSUE TITLE
Exposing /apis/mlj_1/addpicture as non-internal API

### ISSUE THREAD

**Issue by gBasil** [krateng/maloja#169]
Hello!

Would it be possible to have the `/apis/mlj_1/addpicture` marked as a non-internal endpoint? It would be nice to be able to update the track art via the same API keys used to record scrobbles without having to restart Maloja or to generate user authentication cookies from the login password.

My use case: I'm working on a personal project, a website for playing music. I already have the album art stored there, and would like to sync that with Maloja.

Thank you for your time!

**Comment by krateng** [comment]
It should now work with API keys!

**Comment by gBasil** [comment]
Thank you!
