### ISSUE TITLE
Only half sized Pictures/Tiles with Safari

### ISSUE THREAD

**Issue by Mikei386** [krateng/maloja#172]
I'm just done setting up Maloja in combination with multi-scrobbler and Navidrome.
It actually works pretty sweet. 

The only issue I see is with my Safari browser, all Pictures/Tiles on the frontpage are only shown the bottom half.
In every other browser it works perfectly. 

Safari:
<img width="936" alt="Bildschirm­foto 2022-11-27 um 18 58 10" src="https://user-images.githubusercontent.com/44135113/204152073-904dd1f3-b6c5-4f7b-ab24-acac7bdeffb6.png">

Chrome:
<img width="934" alt="Bildschirm­foto 2022-11-27 um 19 03 55" src="https://user-images.githubusercontent.com/44135113/204152141-d22b0e57-c21c-40cf-b4bb-797fe2e7ce4f.png">

**Comment by krateng** [comment]
Does the dev tool console show anything? If you open those same image URLs in a new tab, do they load correctly?

**Comment by Mikei386** [comment]
I'm not quite sure how to access the dev tool console (running in docker). 

When viewing the Artist's Page with Top Tracks the pictures look fine.

Frontpage:
<img width="1673" alt="Bildschirm­foto 2022-11-27 um 19 43 52" src="https://user-images.githubusercontent.com/44135113/204153836-6a39e56d-7298-4b0a-83d9-361db5c29e6d.png">

Artists Page:
<img width="1673" alt="Bildschirm­foto 2022-11-27 um 19 44 07" src="https://user-images.githubusercontent.com/44135113/204153862-43b589ba-6818-4c80-b76b-b0e816248917.png">

So it appears to be only the left column on the first page. 
I'm very thankful for your help and excuse my bad English, I'm from Germany.

**Comment by krateng** [comment]
You can write in German if you prefer, I understand both :)

With dev tools I mean the ones in Safari. They should be under Safari > Settings > Advanced or something like that. Can you open them, then reload the start page and check if there are any error messages in the console?

**Comment by Mikei386** [comment]
Ich bin leider kein Webentwickler und dann noch in Englisch macht es etwas schwer. ;-)

Anbei ein paar Bilder der Konsole.
![Bildschirm­foto 2022-11-28 um 06 40 42](https://user-images.githubusercontent.com/44135113/204203411-1edbc664-2b31-4cfd-9217-81e9f93d613a.png)

![Bildschirm­foto 2022-11-28 um 06 42 47](https://user-images.githubusercontent.com/44135113/204203425-8df40834-9a49-497a-afdc-59bd71c81776.png)

![Bildschirm­foto 2022-11-28 um 06 43 45](https://user-images.githubusercontent.com/44135113/204203438-157a04d3-d848-4a95-a916-f7436586eb81.png)


Es werden keine Fehler oder ähnliches ausgegeben. 
Auch die Ausgabe im Container zeigt nichts besonderes.
Es scheint allerdings an WebKit zu liegen, da ich das Problem auch auf iPhone/iPad habe.
Ich habe es auch mit der Demo-Seite getestet und das gleiche Problem.

Kann ich dir noch irgendwelche weiteren Angaben geben?
Beim googeln bin ich auf das gestoßen: [https://stackoverflow.com/questions/66903058/why-does-safari-only-render-the-top-of-images-sometimes](url)

**Comment by jan666** [comment]
For me I added a workaround to custom CSS:

```
$ cat custom_css/ios_fix.css
table.tiles_sub.tiles_3x3 td div {
        min-height: 100px;
        min-width: 100px;
}

table.tiles_sub.tiles_2x2 td div {
        min-height: 150px;
        min-width: 150px;
}

table.tiles_sub.tiles_1x1 td div {
        min-height: 300px;
        min-width: 300px;
}

table.tiles_sub a span {
        overflow-wrap: anywhere;
}
```

**Comment by Mikei386** [comment]
> For me I added a workaround for this problem to custom_css:
> 
> ```
> $ cat custom_css/ios_fix.css
> table.tiles_sub.tiles_3x3 td div {
>         min-height: 100px;
>         min-width: 100px;
> }
> 
> table.tiles_sub.tiles_2x2 td div {
>         min-height: 150px;
>         min-width: 150px;
> }
> 
> table.tiles_sub.tiles_1x1 td div {
>         min-height: 300px;
>         min-width: 300px;
> }
> 
> table.tiles_sub a span {
>         overflow-wrap: anywhere;
> }
> ```

Your workaround partly works for me, but not on all Images: 

![Bildschirm­foto 2022-11-28 um 13 14 02](https://user-images.githubusercontent.com/44135113/204275228-58367a65-c9be-4250-9475-01e8ec610f47.png)
 
Same in iOS/iPadOS.

**Comment by jan666** [comment]
Please make sure "$ cat custom_css/ios_fix.css" is not part of you css file.

It's just

```
table.tiles_sub.tiles_3x3 td div {
        min-height: 100px;
        min-width: 100px;
}

table.tiles_sub.tiles_2x2 td div {
        min-height: 150px;
        min-width: 150px;
}

table.tiles_sub.tiles_1x1 td div {
        min-height: 300px;
        min-width: 300px;
}

table.tiles_sub a span {
        overflow-wrap: anywhere;
}
```

**Comment by Mikei386** [comment]
D'oh....
Yeah, now it works.

Not sure why I din't recognized your catalog command and just copied and pasted it :D
I'm no web-developer but I'm curious what the actual problem is...

**Comment by krateng** [comment]
So looks like this is a case of WebKit behaving incorrectly? I'll probably just add that workaround css to the official stylesheet then.

**Comment by jan666** [comment]
I did not really found a reason why. But that height: 100% does now work on Safari, yes.

**Comment by Mikei386** [comment]
I can confirm that the workaround works flawlessly on all my devices ˜iOS/iPadOs, Safari Intel, Safari M1).
Shall I close the Topic or wait until it's implemented?

**Comment by jan666** [comment]
I tried that first but it did not work. That's why I added the px

**Comment by krateng** [comment]
Alright, should now be fixed in the next version. Thanks for providing your css @jan666 !

**Comment by jan666** [comment]
No problem - but I still think there must be a better solution. I was just unable to find it (thats why I did not make a pull request)

**Comment by bbsixzz** [comment]
I wanted to run maloja so bad that it made me take the plunge and finally learn docker.

Running navidrome and maloja now with docker compose, I'm super happy :]

This is the only outstanding issue now, looking forward to the next version.
