### ISSUE TITLE
Version 3 Database Upgrade Failed

### ISSUE THREAD

**Issue by carharv** [krateng/maloja#174]
I have built the latest version of Maloja from source. 

When I go to the web page I am met with a 503 Service Unavailable page saying the database is being upgraded to version 3 and that it might take a while. It's been running for a couple weeks now and it's still unavailable. 

Is there a way to trigger the upgrade again or something? 

Thanks!

**Comment by krateng** [comment]
Would you mind sending me your `.tsv` files?

**Comment by krateng** [comment]
Thanks! Looks like your `2022_6.tsv` file has some encoding error in line 39, not sure where that comes from. The conversion should work if you remove the first bytes of that line.
