### ISSUE TITLE
Addition to `delimiters_informal` doesn't seem to do anything

### ISSUE THREAD

**Issue by sseneca** [krateng/maloja#176]
With `/etc/maloja/settings.ini` set to

```ini
delimiters_feat = ["ft.","ft","feat.","feat","featuring","Ft.","Ft","Feat.","Feat","Featuring"]
delimiters_informal = ["vs.","vs","&","with"]
delimiters_formal = ["; ",";","/"]
```

(I added `with` to `delimiters_informal`), Maloja still parses the following tracks

```
clipping. with Michael Esposito – Pain Everyday
clipping. with Greg Stuart – Invocation (interlude)
```

not as `clipping.` and the other artist, but as `clipping. with Michael Esposito` and `clipping. with Greg Stuart`. I'm probably missing something, does anything stand out?

**Comment by krateng** [comment]
The settings file looks fine and works for me, I can think of two things:

1) Is your Maloja using the correct `settings.ini`? With `maloja info` or in your web interface you can check if you've set a different config directory.
2) Rules and delimiters only apply to new scrobbles, are you maybe only looking at existing ones? These would need to be reparsed.

**Comment by krateng** [comment]
Data directory overwrites the individual choices, so your config file is probably `/mljdata/settings.ini` - check if changing it there works.

**Comment by krateng** [comment]
If you just mount `/mljdata`, the `settings.ini` file is inside there, why the need to mount it separately?

The state directory is most likely the same as your config directory, so simply copying those files should do it. The `auth` folder for example is part of it, so if you can see that, you have the right directory.
