### ISSUE TITLE
How do I get this to work with VLC?

### ISSUE THREAD

**Issue by kitesi** [krateng/maloja#178]
I use VLC for my audio listening. How would I scrobble from VLC? I have read the README, and I'm guessing VLC has to make requests to the server, but I'm not sure how to setup vlc to do so. I have looked in the settings and their is a scrobbler setting which takes in a URL, username and password, but the title is "Submission of played songs to LastFM" so I'm not sure if it would work here. Regardless, I tried it, and it didn't work.

**Comment by FoxxMD** [comment]
@kitesi 

This isn't a true solution for you but as a workaround: if you use linux you can use [MPRIS with multi-scrobbler](https://github.com/FoxxMD/multi-scrobbler/blob/develop/docs/configuration.md#mpris) to scrobbler from VLC to maloja. The MPRIS source is available on `foxxmd/multi-scrobbler:develop` docker image or `develop` git branch.

**Comment by kitesi** [comment]
Thank you, I'll check it out!

**Comment by IcedQuinn** [comment]
VLC's scrobbler still fails with this. I'm not sure if its a skill issue on VLC's part or protocol incompatibility.
