### ISSUE TITLE
Allow specifying custom data directory

### ISSUE THREAD

**Issue by Derkades** [krateng/maloja#18]
I'm trying to make a "proper" docker image for this application so I'd like to store data in `/data` instead of `~/.local/share/maloja`.
Right now it seems pretty much hard coded, I can only change the parent directory:
```py
try:
	DATA_DIR = os.environ["XDG_DATA_HOME"].split(":")[0]
	assert os.path.exists(DATA_DIR)
except:
	DATA_DIR = os.path.join(os.environ["HOME"],".local/share/")

DATA_DIR = os.path.join(DATA_DIR,"maloja")
```

Could you add a DATA_DIR environment variable?

**Comment by krateng** [comment]
This should now work with the variable `MALOJA_DATA_DIRECTORY`.

**Comment by Derkades** [comment]
It works, thanks!
