### ISSUE TITLE
Making artist edits persist?

### ISSUE THREAD

**Issue by sseneca** [krateng/maloja#191]
Tyler, the Creator has a comma in his stage name. Even after editing it, Maloja will always parse this as two separate artists: `Tyler`, and `the Creator`.

Same goes for e.g. King Gizzard & the Lizard Wizard. They have an & in their name and so are parsed as `King Gizzard` and `the Lizard Wizard`.

Maybe a new option that allows the user to specify some artists to not apply the delimiter parsing on would fix this.

**Comment by jan666** [comment]
See `rules`-Folder:

```
 belongtogether  Defines an artist with an ampersand or other delimiter in their name. Otherwise, the artist string will be interpreted as two different artists (except when there are no sp
aces).
```

For example my rules:

```
cat belongtogether.tsv
belongtogether  Disco//Oslo
belongtogether  Booze & Glory
belongtogether  Lulu & Die Einhornfarm
belongtogether  Schreng Schreng & La La
belongtogether  ROi!m- & StrOi!- FahrzOi!ge
belongtogether  Tequila & The Sunrise Gang
```

**Comment by Clusters** [comment]
Why was this closed @sseneca ? 
I have exactly the same issue

**Comment by cheesetosti** [comment]
Might be nice to insert an "automatically add edited artistname to personal_edited.tsv" rules feature
