### ISSUE TITLE
[Interface] Fix alignment and improve pulse truncation

### ISSUE THREAD

**Issue by bbsixzz** [krateng/maloja#195]
Safari Version 16.3 (16614.4.6.11.4, 16614)

The titles are not aligned and the pulse dates are overly truncated, shorten the charts to leave more space for text.

Resolution is 1920x1080 and 90% wide window.

![Screen Shot 2023-02-13 at 16 40 35](https://user-images.githubusercontent.com/47334163/218504791-51a89e3a-dddf-4327-b90b-73e021413a7a.png)

**Comment by krateng** [comment]
The titles aren't actually meant to be aligned, as that is supposed to be its own separate 'side bar', and I'm not sure about forcing the side contents to a specific height. Not sure why the charts have so much less space on Safari, but I can make the bar section a bit narrower.
