### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#2]
Would love to see this dockerized so I can run it as a service on my unraid server

**Comment by krateng** [comment]
Can't docker run any arbitrary process?

**Comment by crameth** [comment]
i think this is relatively easy to accomplish through a Dockerfile that we can use to build an image just for majola.

i would love to help out but i'm not sure if it is all that's required to get this up and running. would love some feedback from people more experienced with setting up docker images, especially on dockerhub.
