### ISSUE TITLE
unclear usage of time_format setting

### ISSUE THREAD

**Issue by SurmanPP** [krateng/maloja#200]
It was unclear to me that the setting wanted a strftime string until I red the source and I still don't know how to set the option.

Setting it to "time_format = %d. %b %Y %H:%M" gives me this error:
`configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%d. %b %Y %H:%M'`
Setting it to "time_format = %%d. %%b %%Y %%H:%%M" gives me(when syncing to disc):
`ValueError: invalid interpolation syntax in '%d. %b %Y %H:%M' at position 0`

**Comment by krateng** [comment]
Hm, there seems to be some error in the way `configparser` handles the interpolation which it's supposed to ignore. I'll look into it, but for now it seems it only works without setting that option at all.

**Comment by krateng** [comment]
Ah my bad, the fix in doreah simply wasn't actually deployed - should work in the next version!
