### ISSUE TITLE
'All time' tab not showing scrobbles

### ISSUE THREAD

**Issue by maxelkins** [krateng/maloja#210]
## Setup

- Using docker
- Maloja image version 3.1.5

## Description

Hello :)

I just set up Maloja, and have been able to import from last.fm following the instructions on the readme.

Even though the import seems successful and I can view scrobbles from previous years, the 'All time' tab on 'Top artists/Top track/Last scrobble' doesn't show anything. 

![image](https://user-images.githubusercontent.com/43481548/234400199-f11aeb0b-705c-406f-b043-d443e19d9523.png)

**Comment by krateng** [comment]
Does this persist after a restart?
