### ISSUE TITLE
[Question] Possible to run headless without portforwarding

### ISSUE THREAD

**Issue by J-onasJones** [krateng/maloja#211]
I am currently working on my own spotify scrobbler and was wondering if it is possible to run maloja in a headless state to only record the listening activity, since my last.fm profile is broken and their support is dogsh*t.

*PS: Very good taste, when I opened the demo, I thought this was my profile for a second.*

**Comment by krateng** [comment]
Could you clarify what you're trying to do? Maloja runs headless by default as it's a command line application; and port forwarding is only necessary if you want to access it from outside a firewalled network.

**Comment by J-onasJones** [comment]
perfect, that's all I needed to know thank You. To clarify: I want to not use the web ui at all and was wondering if not port forwarding it would cause any issues, but I realize now, that that is very unlikely. Thanks for the fast response!

**Comment by FoxxMD** [comment]
@J-onasJones Maloja still needs to be accessible through a port in order for whatever scrobble client you are using to actually scrobble to it. The web ui is not necessary in order to run/manage Maloja but scrobbling is done over HTTP
