### ISSUE TITLE
How to scrobble in Navidrome

### ISSUE THREAD

**Issue by purashy** [krateng/maloja#212]
I am sorry for my noobness.

**My setup:**
Music player/server => Navidrome
Scrobble api/keys used => last.fm + listenbrainz

**My issue:**
Both last.fm and listenbrainz show music i listen to for past hour.
However maloja is still empty with no stats whatso ever.
Running maloja with docker-compose, nothing on my portainer log showing any errors etc.

Thank you in advance for the help.

**Comment by krateng** [comment]
Have you set the URL for your Maloja server in the navidrome environment variables?

**Comment by krateng** [comment]
Yup, that's the one. You might have to disable and reenable the setting and set the API key again in the web interface after that.

**Comment by krateng** [comment]
Oh sorry, the environment variable has to be https://maloja.domain.com/apis/listenbrainz/1/
