### ISSUE TITLE
Musicbrainz Metadata API Support

### ISSUE THREAD

**Issue by mcrosson** [krateng/maloja#22]
[Musicbrainz](https://musicbrainz.org) has an API for getting metadata from their database. Would it be possible to add support for their information catalog to compliment Last.FM/Spotify? I've found that between all 3 sources (Musicbrainz, Last.FM and Spotify) I rarely am missing metadata.

**Comment by krateng** [comment]
I'm currently reorganizing the third party services a bit, as soon as the new system is up and running, I'll add Musicbrainz.
