### ISSUE TITLE
Select date and time for manual scrobble?

### ISSUE THREAD

**Issue by HairyOtter** [krateng/maloja#221]
I've noticed that my maloja instance was missing one scrobble compared to lastfm. Seems a few days ago 1 track was not carried over and I'd like to insert it at the appropriate day and time, which lastfm provides me with.

However if I scrobble that song manually through "admin_manual" it ends up as a current scrobble, which means lastfm and maloja are off by 1 for the days it took me to notice this.

While it doesn't matter in the great scheme of things, I'd really like to have that track in the right place chronologically. Can I manually edit the scrobbles somehow to move it to its place? I'd hate to reimport the entirety of my 250k scrobbles from lastfm simply to satisfy my autism.

**Comment by krateng** [comment]
It's not possible from the web interface, but the data is in the malojadb.sqlite file - look for the `timestamp` column in the `scrobbles` table.

**Comment by HairyOtter** [comment]
I copied malojadb.sqlite to my local machine, edited the timestamp of a newly created scrobble of the same song to the old date and copied it back.
It worked.
Beforehand I tried to use the api with curl to simply "scrobble" the song with the appropriate timestamp but couldn't get past "Internal Server" error so clearly I did something wrong.

Anyhow, now my OCD can rest for a while. Thanks.
