### ISSUE TITLE
How to clear images cache?

### ISSUE THREAD

**Issue by fuelen** [krateng/maloja#224]
I've imported data from Last.fm CSV and I see some images are wrong. Then I've set up last.fm API keys, and I'd like to clear the cache, so proper images could be loaded (I hope so).
How to do this?

**Comment by krateng** [comment]
Deleting the .sqlite file in your `cache` folder and then restarting is probably the quickest way.

**Comment by fuelen** [comment]
Thank you.

I've removed the .sqlite file in `cache` folder, but it didn't unfortunately it didn't solve my core issue - image covers looks like generated randomly. I'll create another issue for this.
