### ISSUE TITLE
File x.json could not be identified as a valid import source

### ISSUE THREAD

**Issue by purashy** [krateng/maloja#228]
Hello,

Issue similar to #215 

I decided to request access to my data from spotify and was able to retrieve all my listenings from 2014 to 2023.

However, when trying to import one of the files (i have gotten 4, ex: 2014-2018.json etc) I receive an error. 

```
/usr/src/app # maloja import 2014.json 
[spotify] Successfully authenticated with Spotify
File 2014.json could not be identified as a valid import source.
[sqldb] Database Cleanup...
[dbcache] Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] System RAM Utilization: 53.6%
[dbcache] 53.6% RAM usage, clearing cache!
[dbcache] Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] Entity Cache: Size: 0 | Hits: 0/0 | Estimated Memory: 72 B
[dbcache] System RAM Utilization: 53.6%
[sqldb] Database Cleanup complete!
```

This happens with all the `json` files.

Below is one of the entries from the json file:

```


ts | "2014-10-14T06:55:44Z"
-- | --
username | "xxxx"
platform | "Windows 7 (6.1.7601; x86; SP1; S)"
ms_played | 21037
conn_country | "xx"
ip_addr_decrypted | "xxx.xxx.xxx.xxx"
user_agent_decrypted | "unknown"
master_metadata_track_name | "More!"
master_metadata_album_artist_name | "Devin Townsend Project"
master_metadata_album_album_name | "Epicloud"
spotify_track_uri | "spotify:track:5Lg73XGjnN5WwZF2RLwX8e"
episode_name | null
episode_show_name | null
spotify_episode_uri | null
reason_start | "unknown"
reason_end | "fwdbtn"
shuffle | false
skipped | true
offline | false
offline_timestamp | 0
incognito_mode | false
```

**Comment by Selfibi** [comment]
I got my spotify data a few days ago. They look like this:
![image](https://github.com/krateng/maloja/assets/83219918/3e427ebf-9b9d-4c80-bb8d-5a41600632b8)

You shouldnt change the file name from the default or it wont be recognized.

**Comment by SirMartin** [comment]
I am having issues with this, I am getting the same error.

![image](https://github.com/krateng/maloja/assets/854646/2060fa69-66ce-4a9c-b421-b8820b71df61)


But I created my own image from the #next-minor-version branch. I can see the albums feature there, but I cannot make the import.

![image](https://github.com/krateng/maloja/assets/854646/f5abf7a2-c067-4c50-8732-2f6220f2920f)

**Comment by krateng** [comment]
Support for that format was only in the master branch, but I'll merge it in

**Comment by SirMartin** [comment]
I have setted Spotify in both, same API key
