### ISSUE TITLE
spotify import not properly including album data

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#231]
I just imported approx 20k scrobbles from 2 years of Spotify extended history data. I [combined the `main` branch with the `next_minor_version` branch](https://github.com/duckfromdiscord/maloja/commit/dc6a549ff6a8990f5eae88142ed160e9224a4842) to bring the new Spotify import feature to the album features, but it seems the album data wasn't imported with the spotify data.

![image](https://github.com/krateng/maloja/assets/113956421/e0eb86ca-f897-4564-a323-9b7111c9b3e8)

Songs that I have already listened to properly merge with the existing scrobbles and have album info.

**Comment by krateng** [comment]
The import isn't actually up to speed yet with the album feature, but I'll work on that.

**Comment by duckfromdiscord** [comment]
Seems to be working now!
