### ISSUE TITLE
Maloja Scrobbler Extension (Youtube Music)

### ISSUE THREAD

**Issue by purashy** [krateng/maloja#234]
Hello,

I decided to add `maloja extension` on my brave browser to scrobble youtube music.

**Issues I have:**

When playing songs on youtube (or youtube music), It does not scrobble. However when listening to music from my server (navidrome), it scrobbles just fine.

Thing is, when i check the extension, it does show that it detects i have youtube music open. But it shows "playing nothing".

I have tried with many songs, And even waited until a song ended.
~Could this perhaps be a browser issue? :thinking:  even tho maloja does detect i have a "youtube music" tab open.~
Also tried this with chromium, it appears the same exact outcome. So not Brave related.

**Specs:**

OS: Arch Linux
WM: bspwm

**Screenshot:**

Here is a screenshot of my maloja instance + API, yet nothing scrobbles on youtube/youtube music.

![image](https://github.com/krateng/maloja/assets/4239073/78866a0f-84b2-4fab-b1b4-836f8398fe72)

**Comment by FoxxMD** [comment]
You could use the [Web Scrobbler](https://web-scrobbler.com/) extension instead. It support Youtube Music and Maloja.         

![image](https://github.com/krateng/maloja/assets/4663766/23b153b8-c539-474c-aa15-9d426d88136d)

* API URL: `https://yourMalojaDomain/apis/mlj_1/newscrobble`
* Token: `Your Maloja API Key`

Or if you want to monitor YT Music across all platforms you can use [Multi-Scrobbler](https://foxxmd.github.io/multi-scrobbler/) with [YT Music configuration](https://foxxmd.github.io/multi-scrobbler/docs/configuration#youtube-music)
