### ISSUE TITLE
[Admin UI][Enhancement] Key management

### ISSUE THREAD

**Issue by mcrosson** [krateng/maloja#24]
Would it be possible to add a key management page under the admin UI?

I'd like to be able to host multiple instances of maloja for friends/family and it'd be very handy if users could manage their keys without having access to the server.

**Comment by krateng** [comment]
I have plans to make settings in general available from the web interface which would enable this and #25. This is however a bit of a bigger rework, so it might be a while until this is possible.

**Comment by mcrosson** [comment]
No rush on my end, I wanted to ask about it more than anything. If you need a tester, feel free to reach out. I plano n keeping maloja as part of my self-hosted music stack 😁
