### ISSUE TITLE
Suggestion: Optimize image cache storage method

### ISSUE THREAD

**Issue by Velocidensity** [krateng/maloja#244]
Currently image cache is rather inefficient. Image for every track is stored as its own record (resulting in duplicates), and images are stored base64 encoded, with `data:` URI prepended, which causes at least 35% of size overhead.

The first issue can be solved by storing every image as an entry with just an ID, and then maintaining a table of track-image references, like the main DB already does for tracks-artists. The second by storing images as bytes, and base64-encoding/generating `data:` URIs on the fly.

My preferred solution, however, would be to store only IDs/paths in the database, and files directly on disk, as is currently done with user-uploaded images. This would also have the benefit of allowing the user to bypass the slower python-based bottle server for static files, and serve them directly with their web server of choice, in my case nginx.

**Comment by krateng** [comment]
This is already implemented in [the next update](https://github.com/krateng/maloja/tree/next_minor_version)
