### ISSUE TITLE
[Admin UI][Enhancement] LastFM/Spotify Key management

### ISSUE THREAD

**Issue by mcrosson** [krateng/maloja#25]
Would it be possible to add upstream api key management to the admin UI?

I would like to host maloja for friends/family but don't necessarily want to use my own last.fm or spotify api keys for their instances. Having an option in the Admin UI for them to setup their own keys would be handy.

**Comment by krateng** [comment]
Well, better late than never :D This should now be possible in the `settings` tab in the admin panel.
