### ISSUE TITLE
Ambiguity with `/apis/mlj_1/charts/tracks`

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#251]
The tracks chart function in the external API appears to [always pass an `artist` key to the internal function](https://github.com/krateng/maloja/blob/next_minor_version/maloja/apis/native_v1.py#L307) that processes the request on L307 of the API script. `forceArtist` is enabled meaning that no matter what, there will be an `artist` passed, **even if it's `None`**. But in the internal database function, [there is a check to see whether that key is passed on L376](https://github.com/krateng/maloja/blob/next_minor_version/maloja/database/__init__.py#L376).

It seems that `forceArtist` should be disabled. If the user attempts to get a track chart with the external API without passing an artist, it will be guaranteed to fail because `artist` is `None` but the key is still there, so that `if` statement will always be `True` despite having a `None` value, and therefore will try to do an operation with a non-existent artist.

Perhaps `forceArtist=True` is a typo, since having it would make that `if` statement redundant, and also causes an error whenever a user attempts to check their general track chart without providing an artist.

**Comment by krateng** [comment]
Jesus, my code is so chaotic. I'm starting to think I should rebuild this whole thing in Rust...

I appreciate the thoroughness in looking into it!
