### ISSUE TITLE
Scrobbles have "album_name" but do not seem to show up in 3.2.0

### ISSUE THREAD

**Issue by cirdanlunae** [krateng/maloja#258]
Upgraded to 3.2.0. My "Top Albums" section is completely empty. When browsing the malojadb.sqlite file, I see that my scrobbles have "album_name", but that doesn't seem to be recognized. Is there a chance my scrobbles are malformed?

Example scrobble:

{"track_artists": ["Avenged Sevenfold"], "track_title": "Trashed and Scattered", "scrobble_time": 1689559678, "album_name": "City of Evil", "track_length": "353"}

**Comment by krateng** [comment]
Right now, the database info isn't upgraded automatically. You can do this with `maloja parsealbums` (might wanna make a backup first), or simply let new scrobbles create the albums over time. I will probably include an automatic upgrade in a later version.

**Comment by cirdanlunae** [comment]
You're a fantastic human. I'll give this a try. Thank you!
