### ISSUE TITLE
Bug: "maloja start" doesn't work when spotify API is used

### ISSUE THREAD

**Issue by wynkenstein** [krateng/maloja#264]
Hi,

since that big update with albums, I cannot start maloja correctly on FreeBSD. "maloja run" seems to work fine (no error messages and everything loads) but with "maloja start" it doesn't go back to shell prompt and gets stuck after last echo (the one about localhost address).

All this only happens if I have an active Spotify app with id and secret configured. It worked fine before the album update. When I remove the Spotify credentials the problem is gone.

**Comment by krateng** [comment]
Can you run from the latest source? #259 fixed the issue with FreeBSD, though I'm not sure why the Spotify API config has an effect on it.

**Comment by wynkenstein** [comment]
Thanks for the quick reply, i'm already on latest source and got that stop fix with pgrep already installed. The problem mentioned still exists

**Comment by wynkenstein** [comment]
oh and btw, when I ^c to terminate, this error shows up:

CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
KeyboardInterrupt:

(I had the same issue with python 3.9, but never tested with 3.10)

**Comment by wynkenstein** [comment]
Sorry for triple posting. Tested with Python 3.10 on FreeBSD, same problem. But also tested on Raspberry Pi4 with Python 3.11
As soon as there is the spotify id and secret saved in settings.ini, the next "maloja start" (and "maloja stop" btw!) command will not terminate back to shell at the end.

**Comment by krateng** [comment]
Do the command still work? Is the server running after `maloja start`?

**Comment by wynkenstein** [comment]
When I ^c out it prompts above error about threading in Python, but after that, the two processes (maloja and maloja_supervisor) are still running, yes.

**Comment by krateng** [comment]
I think that should have fixed it.

**Comment by wynkenstein** [comment]
It's working now. Thanks for the quick fix :)
