### ISSUE TITLE
Question: how to enable MusicBrainz?

### ISSUE THREAD

**Issue by jan666** [krateng/maloja#265]
I have music that's not available on Deezer so maloja can't download the artwork. Most of the music in on MusicBrainz but I can't figure out how to enable MusicBrainz. I tried metadata_providers = MusicBrainz,Deezee but without success. Maloja still only tries to downloaded from Deezer. 

What am I doing wrong? Thanks for help

**Comment by krateng** [comment]
The setting needs to be `[musicbrainz,deezer]` as a list of lower case identifiers.

**Comment by jan666** [comment]
Ah, I already tried with [] but not lowercase...

It looks like Maloja is trying to get it from MusicBrainz now but it does not really work:

```
[thirdparty] Could not get album image for (['Pershing Boys'], 'Zuviel Hoffnung') from MusicBrainz
[thirdparty] Could not get album image for (['Pershing Boys'], 'Zuviel Hoffnung') from Deezer
```

But the artwork is there: https://musicbrainz.org/release/9bd074c0-f50e-4ce9-8448-646d5fe81f0f

**Comment by krateng** [comment]
Musicbrainz does in fact only get track images atm, but might as well expand this... working on it!

**Comment by jan666** [comment]
Nice. Thanks!
