### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by Sohalt** [krateng/maloja#27]
Is there a way to install maloja from source (e.g. using setup.py and not from pypi)?

**Comment by krateng** [comment]
If you download the maloja folder from GitHub as is, it should directly work with 'python3 -m maloja' called in the parent folder. I assume if you copy it into the according folder for your python packages, it should also work globally.

**Comment by PietroArado** [comment]
> If you download the maloja folder from GitHub as is, it should directly work with `python3 -m maloja` called in the parent folder. I assume if you copy it into the according folder for your python packages, it should also work globally.

Running the command you gave results in this:
```
pietro@buster-desktop:~/maloja$ python3 -m maloja
/usr/bin/python3: No module named maloja.__main__; 'maloja' is a package and cannot be directly executed
```

This is the tree of `~/maloja`:
```
pietro@buster-desktop:~/maloja$ tree -L 2
.
├── Dockerfile
├── FUTURE.md
├── install_alpine.sh
├── install_ubuntu.sh
├── LICENSE
├── maloja
│   ├── cleanup.py
│   ├── compliant_api.py
│   ├── database_packed.py
│   ├── database.py
│   ├── data_files
│   ├── globalconf.py
│   ├── htmlgenerators.py
│   ├── htmlmodules.py
│   ├── __init__.py
│   ├── malojatime.py
│   ├── monkey.py
│   ├── __pkginfo__.py
│   ├── proccontrol
│   ├── __pycache__
│   ├── server.py
│   ├── static
│   ├── thirdparty
│   ├── urihandler.py
│   ├── utilities.py
│   └── web
├── README.md
├── requirements.txt
└── scrobblers
    ├── chromium
    └── maloja-scrobbler.zip

9 directories, 22 files
```

If you just need to start the application from sources, you can use the [starting script](https://gist.github.com/PietroArado/3845cc74953a8093dd524a125b81f0ad) that `pip` creates in `~/.local/bin/`, by copying it in the root of the repository (in my case `~/maloja`) and running it as follows. Still, it's not `setup.py`.
```
python3 maloja_start.py start
python3 maloja_start.py stop
```

There is a setup.py file in the `maloja/proccontrol` folder, but it's unrelated to the subject matter.

**Comment by krateng** [comment]
Sorry, my mistake, the command would be 'python3 -m maloja.proccontrol' for the regular commands and 'python3 -m maloja.server' for running the server directly (no setup checks and user file copying)
