### ISSUE TITLE
Option to disable image downloading

### ISSUE THREAD

**Issue by puelp** [krateng/maloja#277]

**Comment by duckfromdiscord** [comment]
What do you mean?

**Comment by puelp** [comment]
I mean as in like I don't want Maloja to try to download artist images, album images, track images.

Your comment gave me an idea so I opened the .ini and set 'metadata_providers = []', which appears to have solved it.

What I did is correct, right? There's no other solution that I'm missing?

**Comment by duckfromdiscord** [comment]
I've never tried it but that sounds right.
