### ISSUE TITLE
Albums with the same name from different Artists

### ISSUE THREAD

**Issue by jan666** [krateng/maloja#282]
I just noticed I have at least two albums which have the same name:

https://music.apple.com/de/album/x/1038242029 and https://music.apple.com/de/album/x/478905464

For Maloja its one album and because the Beatsteaks album has more tracks it belongs to them. I is possible to split the album?

**Comment by krateng** [comment]
Usually the track artists are used as album artists. Did you get your album info from parsing old data? The `--strategy track` would avoid that, but for individual cases, you can just quickly scrobble a fake song with the correct album artist; then assign all relevant tracks to that album with admin mode, then delete the fake scrobble.

**Comment by jan666** [comment]
I got it from parsing old data, yes.

I don't really understand how to assign tracks to different albums :(

**Comment by jan666** [comment]
Ah, the icon is only enabled when Association is not done in a new tab.

But it does not work for me. It shows "Success... was added to X" but nothing changed
