### ISSUE TITLE
Large database operation across all scrobbles

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#288]
It seems that the time on my server running maloja is wrong. It has always been wrong I believe, since I've started using maloja. The issue is, I can't just change the time of every scrobble because some of them are imported from Spotify. Lucky for me, scrobbles from different sources are tagged differently! I am very thankful for this feature. Now, I need help selecting all scrobbles that don't have `"origin": "import:spotify"` and offset their times by a certain amount of minutes. Is this possible, and if so, how do I do it?

**Comment by FoxxMD** [comment]
in a sqlite editor

```sql
update scrobbles
set "timestamp" = "timestamp" - 5 /* number of seconds to offset.  subtract => 5 seconds earlier -- add => 5 seconds later*/
where origin != 'import:spotify'
```

**Comment by duckfromdiscord** [comment]
It was a display issue. I had to set `timezone`. Good catch and thank you.
