### ISSUE TITLE
Toggle for Maloja to use a collage of related images when direct image is not available

### ISSUE THREAD

**Issue by puelp** [krateng/maloja#291]
I disabled all image downloading as I described here: https://github.com/krateng/maloja/issues/277#issuecomment-1793600057

(reason being, the images that Maloja downloaded were frequently wrong, really low-quality, and so not that pleasing to look at)

I instead decided to manually add high-quality album covers to 'maloja/images/albums'.

Now the only thing left for me to do was to do the same for artists (whose pages are displaying placeholder microphone icons in place of artist images).

But then I stopped and thought, "Hold on. Wouldn't it be great if Majola automatically took the album covers, processed them into a collage, and used that as the artist picture if an artist image couldn't be found?"

The collage pic could be used elsewhere like another album by said artist without a linked album cover image.

All optional with a toggle in the web settings/.ini, of course.

**Comment by krateng** [comment]
Creative idea, but it's a bit outside of the scope of the project I'm afraid ;) Don't wanna add too many bells and whistles.
