### ISSUE TITLE
Is the check for `mknod` really needed?

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#295]
When you run maloja and it starts to set up its data folders, before it chooses a data folder it runs a short check for permissions. One of the operations it does here is `mknod` at [pkg_global/conf.py L32](https://github.com/krateng/maloja/blob/master/maloja/pkg_global/conf.py#L32C2-L33C31). This will immediately fail if the operation is not permitted. [Maloja itself never actually uses mknod](https://github.com/search?q=repo%3Akrateng%2Fmaloja%20mknod&type=code), so I think this can safely be removed..

**Comment by krateng** [comment]
No longer applicable due to 7d67530
