### ISSUE TITLE
Albumless tracks

### ISSUE THREAD

**Issue by SirMartin** [krateng/maloja#296]
Hi, I found the section with albumless tracks, and the question is, there is any way to assign an album to these tracks? I found, that if I listen the song, it disappears from there, that's quite smart, but still I have almost 50-100 songs there. Is any other way to assign an album?

**Comment by krateng** [comment]
Activate admin mode, then click the little pin next to the tracks. Go to the album page, then click `Add to album` in the top right icon bar.

**Comment by SirMartin** [comment]
Ok, I marked the pin, but I cannot found the album page, or nothing at the top right. Where it is?

![image](https://github.com/krateng/maloja/assets/854646/385d0c7b-002d-4e92-af3e-1a59b25707f3)

**Comment by SirMartin** [comment]
Ok, I more or less found it, and make it work, also I found that if you listen the albumless song, it fills correctly later.

The only problem I found, that with the searchs, and open an album sometimes is incredible slow.

**Comment by SirMartin** [comment]
@krateng is any other way to set up 100s of tracks to albums? I can see that in the album less page only appears a top of them? There is a way to have a count of the total? I will maybe try to find and show the count somewhere else.

**Comment by SirMartin** [comment]
I tested the part of re-importing from lastfm for example, and it does not import or change anything.

**Comment by SirMartin** [comment]
I found that I have around 13k tracks without album, so I think I will try a clean Maloja installation 😜
