### ISSUE TITLE
Move songs from album to another one

### ISSUE THREAD

**Issue by SirMartin** [krateng/maloja#298]
Hi,

In my way to have all the albumless tracks in order, I spent some time today, and I found an kind of issue, I have this track.
![image](https://github.com/krateng/maloja/assets/854646/3ceca688-f526-48b1-8cd9-5914d18f6af6)
This track is associated to the single album, but also appears in the normal album (named _Surrender_), if I listen from the _Surrender_ album (I am using MultiScrobbler to scrobble from Spotify) it counts in the single version.

I tried to move this scrobbles to the real album, I marked with the pin, and in the _surrender_ album, I click on the folder, but it didn't really work, still appears at is own. I tried to use the merge options, but I cannot find a way to make it work, I tried marking both albums as ready to merge, but I don't know how to continue.

What can I do in this case?

**Comment by krateng** [comment]
You only have to mark for merging on the single album, then click the actual merge button on the target album.

**Comment by SirMartin** [comment]
Ok, I am feeling stupid, I think my problem is that sometimes I opened new tabs, so it doesn't work quite well, I just tried on the phone, same tab, and works perfectly.

Thanks again for your work
