### ISSUE TITLE
JSON native scrobble broken since 2.7.8

### ISSUE THREAD

**Issue by ICTman1076** [krateng/maloja#31]
For /api/newscrobble, passing the scrobble as keys works fine:

![image](https://user-images.githubusercontent.com/16071013/91709961-68348a80-eb7b-11ea-9860-af465571dfbe.png)

But passing it as JSON returns 403:

![image](https://user-images.githubusercontent.com/16071013/91709818-315e7480-eb7b-11ea-9e12-cf06e41168a2.png)

**Comment by krateng** [comment]
Small oversight in the refactoring, sorry for that! Should be fixed in the next version.

**Comment by ICTman1076** [comment]
No worries, thanks for the quick fix :)

**Comment by ICTman1076** [comment]
It appears this issue has been reintroduced:
![image](https://user-images.githubusercontent.com/16071013/92328156-abe53380-f056-11ea-8860-bdbd02683303.png)

**Comment by krateng** [comment]
I think I found the issue, should work in 2.9.7

**Comment by ICTman1076** [comment]
Yep, resolved, thanks for quick fix again :)
