### ISSUE TITLE
Songs in multiple albums

### ISSUE THREAD

**Issue by SirMartin** [krateng/maloja#311]
Hi, I am finding some issues trying to move songs from one album to another. 

I chose the song to move to another album
![image](https://github.com/krateng/maloja/assets/854646/0ddee1ff-3f22-4823-aabb-238f77a6d4bd)

I press the move button in the new album.
![image](https://github.com/krateng/maloja/assets/854646/17289a5d-f80a-45df-85cc-27e422371809)

It says that works perfectly.
![image](https://github.com/krateng/maloja/assets/854646/8a708fa5-a41f-4290-9cec-c84d52e50f59)

But it doesn´t appear in the album.
![image](https://github.com/krateng/maloja/assets/854646/8356ef15-913a-4f44-89b8-985e8f9747d6)

I checked the logs, and it says that it worked perfectly, but it did not.
![image](https://github.com/krateng/maloja/assets/854646/5bdeb958-361d-4d42-8284-2c9d1fcd6aa4)

**Comment by jan666** [comment]
I have the same issue: https://github.com/krateng/maloja/issues/282#issuecomment-1812036150
