### ISSUE TITLE
`- ?` vs `(?)`

### ISSUE THREAD

**Issue by duckfromdiscord** [krateng/maloja#312]
The big issue with scrobbling both from Spotify/multiscrobbler and from local audio players is that a lot of bandcamp and similar releases don't use the same sort of syntax as Spotify releases. For example, Spotify tracks generally have things like `- Artist Remix` rather than `(Artist Remix)`. Is there a good way to handle this globally with some sort of filter? Right now I have to re-tag all of my tracks to follow Spotify's naming convention if I want to have them scrobble to the same albums/tracks/etc.

**Comment by krateng** [comment]
I'm planning to allow more general regex rules in the future, but currently you'd have to do it individually I'm afraid.
