### ISSUE TITLE
Audioscrobbler returning error 500

### ISSUE THREAD

**Issue by Bestfast** [krateng/maloja#32]
Every audioscrobbler APIs are returning error 500 with both POST and GET requests. 
curl's return:
![image](https://user-images.githubusercontent.com/31173611/93622878-265e6d80-f9de-11ea-8126-d954b77e9283.png)
maloja:
![image](https://user-images.githubusercontent.com/31173611/93622932-38d8a700-f9de-11ea-8748-f513b9877bbc.png)

**Comment by krateng** [comment]
Did you send a message body with the method?

**Comment by Bestfast** [comment]
@krateng this is without any method. If I send method=track.scrobble&u=Bestfast&t=time&a=apikey for example I get "Invalid session key", even if my key is in the authenticated_machines.tsv and it's the first key ever created by maloja. 
The first 500 error seems a typo made by me, but I still don't understand how to scrobble with audioscrobbler. Does maloja use audioscrobbler 1.2 or 2.0? How do I fix the invalid session key?

**Comment by Rfvgyhn** [comment]
You need to make a `auth.getMobileSession` request which returns a json object that contains the session key. You then pass that to your `track.scrobble` requests.

```
POST /apis/audioscrobbler/2.0/
method=auth.getMobileSession
username=username
password=authenticated_machines_key
```

```
POST /apis/audioscrobbler/2.0/
method=track.scrobble
sk=session_key_from_previous_request
track=track_name
artist=artist_name
timestamp=time
```

**Comment by Bestfast** [comment]
I guess it's my fault, @Rfvgyhn solution worked. Thanks.
