### ISSUE TITLE
Maloja ignores album information for tracks that appear on two albums

### ISSUE THREAD

**Issue by Bujiraso** [krateng/maloja#320]
# Background
I have a greatest hits from a band named The Smithereens, as well as one of their full albums.
I scrobbled that and then listened to the other album.
Maloja erroneously discards the album information and groups it under the greatest hits album

## Expected Result
Album information is used to determine the album

## Actual Result
Artist + Track information is all that is used to determine the album

# Screenshots & Logs

## Incorrect album relationship shown on the UI
![image](https://github.com/krateng/maloja/assets/1975771/4b8df740-3ec3-4c29-87b9-566b256508f4)

## Incorrect album association on the track
![image](https://github.com/krateng/maloja/assets/1975771/7c0f48d3-c58f-4890-ba68-62324ae72101)

Also the thumb art is totally wrong. Minor bug.

## Database kept good records
The database shows that it kept the scrobble info, and that it sees the album title.
```sql
1704551778|{"track_artists": ["The Smithereens"], "track_title": "Top of the Pops", "album_title": "Blow Up", "track_length": 273, "scrobble_time": 1704551778}|client:iTUInes||21104|{"album_title": "Blow Up", "album_artists": ["The Smithereens"]}
```

## Reparse does nothing
![image](https://github.com/krateng/maloja/assets/1975771/cebe8a69-50fd-4482-817e-e79e0979da34)

**Comment by krateng** [comment]
This is working as intended. Albums are associated with tracks, not with individual scrobbles, so you can only have it on two albums if it's two different tracks (like 'Album Version' or smth).

**Comment by Bujiraso** [comment]
hey @krateng , would it be possible to switch the album association? Or re-open this as a feature request?

I would love to know more about why this is intended, whether from a user or dev perspective.
