### ISSUE TITLE
Legacy Audioscrobbler protocol

### ISSUE THREAD

**Issue by p182** [krateng/maloja#35]
Some clients still use legacy protocol, such as scrobblers for portable devices, old-school players etc.
Documentation: https://web.archive.org/web/20190531021725/https://www.last.fm/api/submissions

**Comment by ICTman1076** [comment]
Would these legacy clients allow you to change domain or path though? It would be awkward to implement otherwise, especially if you can't change domain because that would mean some DNS trickery would be required to get those clients working.

**Comment by Rfvgyhn** [comment]
One such client that I use is [mpdscribble](https://github.com/MusicPlayerDaemon/mpdscribble). It supports specifying your own url.

**Comment by p182** [comment]
We can recompile with new URL or replace it in binary, also it don't problem to change hosts file to specify own IP address, so having legacy protocol in Maloja have sense.

P. S. I need it to submit my scrobbles (more than 2000 cached scrobbles) from foobar2000 using legacy foo_audioscrobbler (I can change submissions URL in binary) and to use with maemo-scrobbler (it has source)

**Comment by ICTman1076** [comment]
> We can recompile with new URL or replace it in binary, also it don't problem to change hosts file to specify own IP address, so having legacy protocol in Maloja have sense.
> 
> P. S. I need it to submit my scrobbles (more than 2000 cached scrobbles) from foobar2000 using legacy foo_audioscrobbler (I can change submissions URL in binary) and to use with maemo-scrobbler (it has source)

I have already made a fb2k scrobbler which will work for servers on port 80 or 443 - https://github.com/ICTman1076/foo_maloja

**Comment by p182** [comment]
You didn't quite understand me correctly, I have more than 2000 scrobbles in foo_audioscrobbler and I need to send them to Maloja, can you recommend a workaround for this?

A PHP proxy for legacy protocol to native will be better than native support for the legacy protocol?

**Comment by ICTman1076** [comment]
Oh, I see, you mean you have an offline cache of scrobbles to submit? Well from my very brief research and testing I _believe_ that despite the legacy protocol being deprecated lastfm will still accept scrobbles from it. So you could create a temporary last.fm account, then scrobble your backlog to it, then [follow the first bullet point on the README under data](https://github.com/krateng/maloja#data) to import it.

**Comment by p182** [comment]
> create a temporary last.fm account, then scrobble your backlog to it

That's not workaround since last.fm doesn't accept scrobbles older than 14 days

**Comment by ICTman1076** [comment]
I'm working on a PR - it seems that the API needs to tell the client at handshake the endpoints to which it scrobbles, and to do that the API will need to know its own protocol, port and domain (3 things I am unsure of how to get) so if anyone knows that would be useful for me, thanks :)

**Comment by p182** [comment]
As I understand from https://github.com/krateng/maloja/blob/master/maloja/server.py Maloja use Bottle webserver for APIs, so we can get these variables from HTTP request headers via Request objects field headers (https://bottlepy.org/docs/dev/api.html#bottle.Request)
Domain and port in Host header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)

**Comment by Rfvgyhn** [comment]
It looks like don't have to parse the headers your self. Bottle provides a `urlparts` property. https://bottlepy.org/docs/dev/api.html#bottle.BaseRequest.urlparts

**Comment by ICTman1076** [comment]
It does, but it appears that [none of this is passed through to nimrodel](https://github.com/krateng/maloja/blob/master/maloja/apis/_base.py), so I don't know how I could access headers in the API class without fundamentally changing the way that the apis work

**Comment by Rfvgyhn** [comment]
I don't know bottle or python, but it looks like [nimrodel sets `server` to an instance of bottle](https://github.com/krateng/nimrodel/blob/90ae9f51a0d3dbd7e10dab939d9139d4ffaacb68/nimrodel/_api.py#L53). Would that provide that access you need?

**Comment by ICTman1076** [comment]
Unfortunately not. That same file does point to the handler passing headers though (line 151) but Maloja's handler totally misses out this argument.

**Comment by p182** [comment]
I don't know python but I suggest that class name in audioscrobbler (API 2.0) and legacy_audioscrobbler (1.2) should be different, and we need to add legacy_audioscrobbler in https://github.com/krateng/maloja/blob/master/maloja/apis/__init__.py, right?

**Comment by krateng** [comment]
2.10.1 now has experimental support for the legacy protocol, let me know if it works!
