### ISSUE TITLE
Can't get scrobbling to work with Spotify

### ISSUE THREAD

**Issue by aftraid8** [krateng/maloja#354]
I just found this project and really like the idea of it. The problem is I can't get the scrobbling work.

I run Maloja on a Debian 12 server with Docker Compose and the setup was no problem. 
I did create an app in the developer.spofify.com page on Spotify and filled in the API ID and secret in my compose file. I thought this would be fine, but it seems not.

I've read all of the documentation but I didnt get any wiser of that. What did I miss out?

There was one thing i had no idea what i should put in "Redirect URIs" at the create app page of Spotify.

Maloja start fine and i dont get any errors.

**Comment by duckfromdiscord** [comment]
Are you using a scrobbler? The Spotify API key maloja itself takes is for getting song art, you need a scrobbler like multi-scrobbler to do the actual scrobbling part. maloja is a scrobbling _server_ and you need a client.

**Comment by aftraid8** [comment]
> Are you using a scrobbler? The Spotify API key maloja itself takes is for getting song art, you need a scrobbler like multi-scrobbler to do the actual scrobbling part. maloja is a scrobbling _server_ and you need a client.

That was a bit stupid of me. Working great now :)
