### ISSUE TITLE
Move a song from an album to another

### ISSUE THREAD

**Issue by fratt-elca** [krateng/maloja#363]
Hello,

I have a song who was assigned an album, and I would like to move it to a different album.

I tried to click on ![image](https://github.com/krateng/maloja/assets/60597929/dd74141e-8d3c-4f3c-915f-49b559e21b68) on the song, and then on ![image](https://github.com/krateng/maloja/assets/60597929/0405b7bf-0e90-4370-9506-a20536ffdadf) on the album, but nothing happens.

Is this a bug?

Thanks!

**Comment by fratt-elca** [comment]
The fact that this popup shows up, and the track was not moved, confirms me that it's a bug : 

![image](https://github.com/krateng/maloja/assets/60597929/e623b3eb-e742-4400-a0ab-db8a76a92960)

I'm using Maloja 3.2.2

**Comment by fratt-elca** [comment]
For me, it never works in any scenario.

The solution I have found is to shut down Maloja and manually update the rows in the SQLite database.

**Comment by SirMartin** [comment]
Ok do you use the latest release? Try to build a new docker image manually, so you can get the latest changes on master, there is a big difference

**Comment by fratt-elca** [comment]
I'm using the latest release, yes (3.2.2). I'm not building the current master, no.

**Comment by fratt-elca** [comment]
You're right, it's fixed in the upcoming version it seems : https://github.com/krateng/maloja/commit/fd4c99f88898ff978df7ccb5a1a958f478b07910

**Comment by fratt-elca** [comment]
Fixed in upcoming version.
