### ISSUE TITLE
Chromium 86 (Linux) with maloja web extension v1.6 settings not sticking?

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#38]
Hi there

I am struggling to get my local maloja server settings to stick in the web extension settings?

I add them and both fields go green, but once the dialog loses focus and I click on the settings icon again, the settings are reset.

Must be something I am missing :)

Thanks in advance

**Comment by krateng** [comment]
I can't reproduce this at the moment. Could you open your dev tools (right click on the little settings panel and select "inspect element") and then again try to enter your details and see if there's anything showing up in the console?

**Comment by mannp** [comment]
Hi there, thanks for your help :+1: 

`localhost:42010/api/test?key=BlackPinkInYourArea:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
settings.html:32 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

settings.js:64 GET chrome-extension://dkkbnallfgdemnlhjnlfkkchjffolffn/jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca/api/test?key=BlackPinkInYourArea net::ERR_FILE_NOT_FOUND
checkServer @ settings.js:64
settings.js:64 GET chrome-extension://dkkbnallfgdemnlhjnlfkkchjffolffn/jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca/api/test?key=BlackPinkInYourArea net::ERR_FILE_NOT_FOUND
checkServer @ settings.js:64
settings.html:35 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

settings.js:64 GET chrome-extension://dkkbnallfgdemnlhjnlfkkchjffolffn/jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca/api/test?key=jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca net::ERR_FILE_NOT_FOUND
checkServer @ settings.js:64
settings.js:64 GET chrome-extension://dkkbnallfgdemnlhjnlfkkchjffolffn/jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca/api/test?key=jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca net::ERR_FILE_NOT_FOUND
checkServer @ settings.js:64
settings.js:64 GET chrome-extension://dkkbnallfgdemnlhjnlfkkchjffolffn/jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca/api/test?key=jBUUwFTJakCcpcpvfbTAsDQnsgHAXxHSPMDVZnuFpxnDMAswRBhqxmDfBakFeSca net::ERR_FILE_NOT_FOUND
checkServer @ settings.js:64`

**Comment by mannp** [comment]
I get the following two errors only;

settings.html:32 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

settings.html:35 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by krateng** [comment]
Hm, so this seems to be a security restriction - not sure why it doesn't trigger for me. Which exact flavor of Chromium do you use?

**Comment by krateng** [comment]
Hm, it looks like that is the default and my browser is just insecure :D I changed it in the included zip. Do you install from the web store? In that case I"ll upload it there too, but it might take a few days until it's approved.

**Comment by mannp** [comment]
Version 86.0.4240.75 (Official Build) Arch Linux (64-bit)

Lol, okay fair enough.

I tried both but currently have the included zip installed, so will download your update, thanks.

**Comment by mannp** [comment]
I can confirm this update works, thanks for the quick turnaround :)
