### ISSUE TITLE
Not accessible outside localhost

### ISSUE THREAD

**Issue by mayvaneday** [krateng/maloja#4]
Installed Maloja on a fresh Debian 9 VPS, installed the dependencies with ``pip3 install -r requirements.txt``, and ran ``./maloja start`` as according to the instructions. I can access it on localhost on the VPS, but I can't access it from any outside devices. UFW is disabled, and the port seems to be open, and nothing relevant is in the system logs.

**Comment by sentriz** [comment]
Maybe the servers bind address needs to be `0.0.0.0` if it's localhost currently

**Comment by mayvaneday** [comment]
Is binding to 0.0.0.0 a hidden option somewhere? I've scoured the documentation and settings files high and low, and I can't find anything regarding this.

**Comment by krateng** [comment]
Are you potentially on IPv4 only? The server listens on ::, meaning it's only accessible via IPv6. The relevant line would be the last one in server.py, but I could make that a setting if required.

**Comment by mayvaneday** [comment]
That seems to be the problem. I added an IPv6 address to my VPS, and the problem appears to be solved.

I think adding an option to change where the server listens would be a good option, if not stating in the README that it only runs on IPv6.
