### ISSUE TITLE
Native browser extension not scrobbling from Chromium

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#40]
Chromium 86 (Linux) with maloja web extension v1.7 doesn't scrobble with Deezer in the browser?

I checked the plugin inspect popup and nothing, as well as the plugin config is green and ticking now :+1: 

I first tried only allowing selected urls to be tracked, which didn't work, so I tried allowing everything in the plugin settings but that doesn't scrobble either.

**Comment by krateng** [comment]
The extension only works for Plex, Spotify, Bandcamp, Soundcloud and YouTube Music, sorry!

**Comment by mannp** [comment]
LOL I'd missed that then, don't use any of them, thanks anyway :)

**Comment by FoxxMD** [comment]
@mannp try using [web-scrobbler](https://github.com/web-scrobbler/web-scrobbler) (configuration [in the docs](https://github.com/krateng/maloja#standard-compliant-api)). Works perfectly

**Comment by mannp** [comment]
> @mannp try using [web-scrobbler](https://github.com/web-scrobbler/web-scrobbler) (configuration [in the docs](https://github.com/krateng/maloja#standard-compliant-api)). Works perfectly

Thanks @FoxxMD I have it working :+1:
