### ISSUE TITLE
Mixed content error for https behind traefik2 - Seems some requests are http?

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#41]
Hi there

I have my instance behind a traefik2 proxy but it seems that some of the requests being made for cover art are http.

> http://coverartarchive.org....

While coverartarchive appears to have https access available.

I haven't specifically requested coverartarchive so cannot tell which option has enabled it.

I currently only have last.fm api configured.

Thanks

**Comment by krateng** [comment]
Coverartarchive is included automatically as it requires no API key. Apparently the API returns http links per default, but I've changed it to automatically upgrade (I assume they can serve every image they have also with SSL).

**Comment by mannp** [comment]
Thanks for the quick update :+1:

**Comment by mannp** [comment]
@krateng don't suppose there might be a release due to incorporate this one into pls? :)

**Comment by krateng** [comment]
Should be included in 2.10, does it not work?

**Comment by mannp** [comment]
> Should be included in 2.10, does it not work?

I have not tried it as using docker and it downloads a release rather than git.

**Comment by krateng** [comment]
The release on pypi is 2.10 as well. I assume your docker container caches the old version - adding the according flag to the command should avoid that.

**Comment by mannp** [comment]
Thanks, will try tomorrow 😃

**Comment by mannp** [comment]
> Should be included in 2.10, does it not work?

I have rebuilt my docker, cleared the cookies and cache for my site  and confirmed I am on 2.10 but the same issue persists.

http://coverartarchive.org/ is still the culprit.

I wondered why it isn't doing the same on yours and other instances.

Perhaps as i don't have spotify configured, so it has to go to coverartarchive instead?

**Comment by krateng** [comment]
Did you also clear the server cache (stop the server, delete the folder `cache` in your maloja folder, then restart the server)?

**Comment by mannp** [comment]
> Did you also clear the server cache (stop the server, delete the folder `cache` in your maloja folder, then restart the server)?

I didn't initially but I have done since adding the spotify api to my config.

All my artists have now been populated with pictures and https is confirmed.

That said I very occasionally get the browser saying mixed content, so I am not sure if the issue is fixed or just the vast majority of the covers are now https supplied by spotify.

Not sure if there is a way to check if any of my cache is http.

**Comment by krateng** [comment]
Whenever you get the warning, you can check on that page (sources or network tab in the dev console) which images are actually the problem.

**Comment by mannp** [comment]
> Whenever you get the warning, you can check on that page (sources or network tab in the dev console) which images are actually the problem.

Yes that is how I have done it thus far, so will keep an eye on it.

Yesterday before spotify it was still coverartarchive.
