### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by tukhabheja** [krateng/maloja#43]
Hi! I'm very new to docker, but I wanted to setup this project cause it seems really cool. I am using joniator's maloja repository. I have docker setup, and I downloaded the image. However when I enter this command:

`$ sudo docker run -p 8080:80 joniator/maloja`

I get this output:

Initializing database...
No existing database found.
New database class defined: <class 'doreah.auth.User'>
Database saved to disk.
New database class defined: <class 'doreah.auth.Session'>
Database saved to disk.
Various external services can be used to display images. If not enough of them are set up, only local images will be used.
	Please enter your Last.fm API Key. If you do not want to use one at this moment, simply leave this empty and press Enter.

Traceback (most recent call last):
  File "/usr/local/bin/maloja", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/doreah/control.py", line 47, in wrapper
    return func(*args,**kwargs)
  File "/usr/local/lib/python3.8/site-packages/maloja/proccontrol/control.py", line 91, in main
    if action in actions: actions[action](*args,**kwargs)
  File "/usr/local/lib/python3.8/site-packages/maloja/proccontrol/control.py", line 72, in direct
    setup()
  File "/usr/local/lib/python3.8/site-packages/maloja/proccontrol/setup.py", line 46, in setup
    key = prompt("",types=(str,),default=None,skip=SKIP)
  File "/usr/local/lib/python3.8/site-packages/doreah/io.py", line 65, in prompt
    inp = getpass("") if secret else input()
EOFError: EOF when reading a line

Docker is also not running. I googled EOFError: EOF when reading a line and it says it is a python error. Please let me know what I can do to fix it.

Thanks in advance!

**Comment by krateng** [comment]
Have you set the environment variable MALOJA_SKIP_SETUP?

**Comment by Rfvgyhn** [comment]
You need to mount a data volume and specify that you want to skip setup with the `MALOJA_SKIP_SETUP` environment variable.

1. Create a folder on your host machine where you want to store things like configuration and the database.
    `mkdir /home/user/maloja/data`
2. Specify the parameters in your docker run statement
    `docker run -e MALOJA_SKIP_SETUP=true -v /home/user/maloja/data:/root/.local/share/maloja -p 8080:80 joniator/maloja`

**Comment by tukhabheja** [comment]
Thanks that is exactly what I was doing wrong! It now says the container is running. I have one more question. How to you connect to the web interface? I tried `localhost:8080` , but it says it cannot connect. However, I did give docker permission. Any ideas?

**Comment by Rfvgyhn** [comment]
Maloja doesn't run on port 80. Try mapping to to 42010 instead. `-p 8080:42010`.

**Comment by tukhabheja** [comment]
I realized that too, and tried mapping it to 42010. When I try to connect, it says "The connection was reset". I think maybe its a problem with the port not having access, but I already configured it with `sudo groupadd docker`. Any ideas?

**Comment by Rfvgyhn** [comment]
Try setting `HOST` to `0.0.0.0` in your mounted `settings/settings.ini` file.

**Comment by tukhabheja** [comment]
That's probably the issue. However when ever I edit the file to `0.0.0.0` , it only saves temporarily. When I start the container, it goes back to `::`. I did go in as root. Do I have to edit another file too?

**Comment by mannp** [comment]
For default.ini note at the top of the file :)

> # Do not change settings in this file
> # Instead, simply write an entry with the same name in your own settings.ini file
> # Category headers in [brackets] are only for organization and not necessary

settings.ini is what you edit.

**Comment by tukhabheja** [comment]
Thanks you so much! It worked when I went to `0.0.0.0:42010`. :-)

**Comment by tukhabheja** [comment]
Now that the server works, how do I log in as admin? I did not read the readme correctly, and did not us `MALOJA_FORCE_PASSWORD`. How do I change it now? Also, every time I run the server, do I have to use `MALOJA_SKIP_SETUP=true` in the run statement? I appreciate you taking time to help me!

**Comment by krateng** [comment]
You should always keep the `MALOJA_SKIP_SETUP` in when you run in Docker. To set a new password, you only need to run it once with `MALOJA_FORCE_PASSWORD`, then can run it normally again.

**Comment by tukhabheja** [comment]
What does `MALOJA_FORCE_PASSWORD` do? I ran `docker run -e MALOJA_FORCE_PASSWORD -v /home/user/maloja/data:/root/.local/share/maloja -p 42010:42010 joniator/maloja` and the went to `0.0.0.0:42010`. I then went to the admin page, and left the `password` and `response` boxes empty, and hit login in. It did not do anything. It's probably my error. Kindly let me know.

**Comment by krateng** [comment]
You need to supply the password you want to set, e.g. `MALOJA_FORCE_PASSWORD=testpw123`
