### ISSUE TITLE
/post.audioscrobbler.com to ? for Slimserver8 (Working)

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#44]
Hi there

I am trying to tweak an old Slimserver plugin to get it to scrobble to my maloja box and wondered if I could just replace the http://post.audioscrobbler.com with my maloja url.

It doesn't seem to work and I wondered if someone could point me too the url I need to get the same api as at 
post.audioscrobbler.com?

I also tried http://my-maloja/apis/audioscrobbler which didn't seem to work either :-/

```
use constant HANDSHAKE_URL => 'http://post.audioscrobbler.com/';
	my $url = HANDSHAKE_URL
		. '?hs=true&p=1.2'
		. '&c=' . CLIENT_ID
		. '&v=' . CLIENT_VER
		. '&u=' . $params->{username}
		. '&t=' . $time
		. '&a=' . md5_hex( $params->{password} . $time );
```

Thanks for any help

Edit: Notice the '1.2' and wondered if that was related to -> https://github.com/krateng/maloja/issues/35

**Comment by krateng** [comment]
Yep, looks like it's using the legacy protocol as well. @ICTman1076 are you still working on this? Otherwise I'll give it a go sometime this week.

**Comment by mannp** [comment]
> Yep, looks like it's using the legacy protocol as well. @ICTman1076 are you still working on this? Otherwise I'll give it a go sometime this week.

Okay thanks for the fast response and confirmation.

If you have time, a legacy update would be great :+1: 

Would this result in maloja being a drop in replacement for  http://post.audioscrobbler.com ?

I don't know about Roon as its closed source, but their last.fm support was added some time ago and doesn't appear to have been updated, so they are also likely using the legacy api.

**Comment by krateng** [comment]
2.10.1 now has experimental support for the legacy protocol by replacing the URL with `https://yourserver.tld/apis/audioscrobbler_legacy`. Let me know if it works!

**Comment by mannp** [comment]
Great news, thanks :)

I wondered what the reason (aside from more effort etc) would be that maloja couldn't redirect to the correct endpoint depending on the api being requested?

The reason I ask is I was going to change the IP of the post.audioscrobbler.com on my opnsense firewall and have every device using lastfm use maloja without any configuring of apps :)

**Comment by krateng** [comment]
That would mean exposing the API at the root path, which would massively break the organization of the server and require really ugly routing logic, so I don't think that's gonna be possible, sorry!

**Comment by mannp** [comment]
> That would mean exposing the API at the root path, which would massively break the organization of the server and require really ugly routing logic, so I don't think that's gonna be possible, sorry!

Okay :) thanks for the explanation.

I am getting closer to getting this working, just debugging at the moment.

In the config for my existing real lastfm user has the following;

```
  password: hfgihufgiohugiohudioghuoifg
  session_key: fgkjhkldfgjhfhjgklhjfgklhjkfldg
  subscriber: '0'
  username: mannp 
```
I have copied and pasted it in the config to a maloja user as the plugin appears to do some checking the account exists, which of course it doesn't on lastfm.

Is the session key created by the api, so I should delete it from the copied config?

I am getting a 404 at the moment, not sure why...

`[20-10-29 18:17:19.0171] Slim::Plugin::AudioScrobbler::Plugin::_handshakeError (373) Error handshaking with Last.fm: 404 Not Found`

**Comment by krateng** [comment]
Yeah, the session key can be deleted.

Have you added the trailing `/` after the URL? That's the only thing I can think of right now, obviously I don't really know what the plugin does. Do you have Postman by any chance or any other way of intercepting API requests? That would help troubleshooting.

**Comment by mannp** [comment]
> Yeah, the session key can be deleted.
> 
> Have you added the trailing `/` after the URL? That's the only thing I can think of right now, obviously I don't really know what the plugin does. Do you have Postman by any chance or any other way of intercepting API requests? That would help troubleshooting.

Thanks I had deleted it but other issues meant I wasn't sure of its effect.

I am changing 

`use constant HANDSHAKE_URL => '**http://post.audioscrobbler.com/**';`

https://maloja.domain/apis/audioscrobbler_legacy/

I do have Postman but have only used in to POST requests via api's etc rather than intercepting api requests.

I will keep trying, I might make some progress :)

**Comment by mannp** [comment]
I am trying this from the music docker

`curl -X POST http://192.168.10.97:42010/apis/audioscrobbler_legacy?key=ghdfgdfghdfghdfghdfjkghjkdf&title='The Way I Feel'&artist=Keane`

It returns HTML??

```
<html>

        <head>
                <title>Maloja - Error</title>
                <meta charset="UTF-8" />
                <meta name="description" content='Maloja is a self-hosted music scrobble server.' />

                <link rel="stylesheet" href="/style.css" />

                <script src="/search.js"></script>
                <script src="/neopolitan.js"></script>
                <script src="/upload.js"></script>

        </head>
```

**Comment by krateng** [comment]
`curl "http://192.168.10.97:42010/apis/audioscrobbler_legacy/scrobble/?s=ghdfgdfghdfghdfghdfjkghjkdf&t=The%20Way%20I%20Feel&a=Keane"`

This should work.

**Comment by mannp** [comment]
> `curl "http://192.168.10.97:42010/apis/audioscrobbler_legacy/scrobble/?s=ghdfgdfghdfghdfghdfjkghjkdf&t=The%20Way%20I%20Feel&a=Keane"`
> 
> This should work.

Unfortunately not.

It just keeps returning the same html.

Will take a step back and try to understand what is happening.

**Comment by krateng** [comment]
Strange, it at least should not show HTML. Are you sure you've updated to 2.10.1 (pip caches per default)?

**Comment by mannp** [comment]
Mmhh, that will teach me not to assume updating docker updates maloja :+1: 

I can only assume  2.10.1 is not in the Py repository when the docker image is built.

**Comment by mannp** [comment]
I have tweaked my docker so all dependencies are up to date and the latest version of maloja is now pulled in correctly.

Will try all this again :+1:

**Comment by mannp** [comment]
Okay some progress...

`curl "http://192.168.10.97:42010/apis/audioscrobbler_legacy/scrobble/?s=password&t=The%20Way%20I%20Feel&a=Keane"`

BADSESSION#

**Comment by mannp** [comment]
Turns out the password was encoded in the file so converting the real password and re saving the config worked :+1:
