### ISSUE TITLE
Today lost all my Top Artist cover art from the top left?

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#45]
After clearing the cache directory of the docker and adding spotify, I managed to get all of the top left artists populated and life was good :+1: 

Today I went to my maloja page and all of the artist cover art are gone?

I have checked the thirdparty.log and nothing jumps out, the meta providers register and proceed to get data, some can't find coverart some can, but no other errors?
```
2020/10/28 13:15:16  LastFM registered as metadata provider
2020/10/28 13:15:16  Spotify registered as metadata provider
2020/10/28 13:15:17  MusicBrainz registered as metadata provider
```
Not sure if spotify / lastfm has blocked me, but don't think so as some fetches succeed...?

**Comment by krateng** [comment]
If you inspect the html of those artist tiles, do any URLs show up or are they empty?

**Comment by mannp** [comment]
It appears that my VPN rotated to a country with some sort of geo ban, not entirely sure but rotating the country and all was well.

Apologies for the noise.
