### ISSUE TITLE
Docker update?

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#46]
I am no expert by any means but I wondered if the Docker needed tweaking to always update the dependencies and install from the latest versions ..

```
FROM python:3-alpine

WORKDIR /usr/src/app

# update / dependencies  
RUN apk --update upgrade \
&& apk --no-cache --no-progress add gcc libxml2-dev libxslt-dev py3-pip libc-dev linux-headers \
&& rm -rf /var/cache/apk/*

# install maloja
RUN pip3 install --no-cache-dir psutil malojaserver

EXPOSE 42010

ENTRYPOINT maloja run
```

**Comment by krateng** [comment]
I think an upgrade flag for the pip command should be enough to always get the latest server, the dependencies are reinstalled anyway.
