### ISSUE TITLE
Unpredictable redirects to http from http

### ISSUE THREAD

**Issue by RCAPDART** [krateng/maloja#51]
Hi!
Issue could be reproduced, when maloja is working behind Apache2, which is creating https-host for it.
For example - at this page "**https**://domain-name.tld/admin_overview" UI is trying to get data from "**https**://domain-name.tld/api/serverinfo", after it - it is redirected to "**http**://domain-name.tld/apis/mlj_1/serverinfo". And because of "mixed content" this api-call failed. 
I'm not python dev, but I'm assuming, that the reason is here: https://github.com/krateng/maloja/blob/9a6617b4b1117a6e53d818aadcda886c831e16db/maloja/apis/__init__.py#L35
Bottle.redirect is trying to redirect call and, as it is working on "http" behind the apache - it is redirecting call to the http.

May be possibility to run whole maloja on "https", or setting param to bottle to redirect always to https could solve this.

Or may be I just missed something :)

**Comment by krateng** [comment]
That is strange, it doesn't seem to happen for me with nginx. I'll look into it, but I should also just update the URL to avoid that redirect.

**Comment by RCAPDART** [comment]
Please update this pair too:
"/api/test" -> "/apis/mlj_1/test"
Here: https://github.com/krateng/maloja/blob/22172d8b57df2ad1282f8d835183be45843fdd6a/maloja/web/jinja/wait.jinja#L20

Thank you in advance :)
