### ISSUE TITLE
Slow database build on startup and progress indication

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#54]
I have 70k scrobbles in my database and run maloja in a docker container.

After rebuilding the image database building can take up to 5 minutes:

```
// logs/database.log
2020/11/16 17:50:12  Starting database...
2020/11/16 17:50:12  Building database...
2020/11/16 17:55:55  Database fully built!
2020/11/16 17:55:56  Authenticated Machines: web-scrobbler
2020/11/16 17:55:56  Database reachable!
```

The duration isn't really the issue though -- the issue is that the web server isn't started(?) until after the DB is built so during that 5 minutes it looks like the server is "down". Additionally there is no output to stdout/err so nothing shows up in the docker log output, which is a bit unnerving. I know now to look in `database.log` now but its not obvious and wouldn't be clear to a new user.

**Comment by krateng** [comment]
I will add a progress indication (might take a while though, I'm not getting much done at the moment) - but 5 minutes seems definitely like there is some other issue here, I have 70k scrobbles as well and it takes only a few seconds. Or is your container just limited to very low CPU usage?

**Comment by FoxxMD** [comment]
No cpu bottlenecks, its got two xenon cpus (20 cores) at its disposal. The container sits around 2% cpu usage when the database is building.

**Comment by krateng** [comment]
Alright, there is now a progress bar when starting. I assume stdout gets passed to docker and this solves the issue?

**Comment by FoxxMD** [comment]
There's no progress bar but I do see more output before it gets to building the database, which is helpful! Lack of a dynamic progress bar might be because output is displayed in html so its not a true TTY interface (though the docker output is tailed).

On the issue of performance, could it be that the database work cannot take advantage of multiple cores? Here's what I see metrics wise when the DB is building:
![image](https://user-images.githubusercontent.com/4663766/100932883-8c756f80-34ba-11eb-8393-21025a30da0e.png)

I'm running Xenon Et-2650L (1.7GHz) so they are not that powerful for single core performance but it still seems awfully long...now that I've figured out how to debug maloja I'll see if I can't sus out some hints to this when i have some free time soon.

**Comment by krateng** [comment]
Yes, the app is completely single-cored because of Python's GIL. I feel like at least the db build should still be faster than that though - let me know if you can find anything.

Does the html display nothing at all or does it just render a new partially filled bar for each item?

**Comment by FoxxMD** [comment]
Shows nothing 
![image](https://user-images.githubusercontent.com/4663766/101031261-8d081780-3547-11eb-87f1-2b843e883642.png)

**Comment by krateng** [comment]
I now added an option `CLEAN_OUTPUT` that replaces the loading bar with frequent progress indicators, which should properly show up on the web interface.
