### ISSUE TITLE
Development instructions or jumpstarter?

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#57]
I know your time is limited right now and I apologize for making so many issues!

I'd like to contribute at a deeper level with Maloja by actually submitting PRs for the fixes and stuff I've been asking for but I am not a python developer and don't really have a clue or where to start when jumping into development for Maloja.

I have 8 years of professional development experience in JS, PHP, and C# and have the tooling I probably need (Jetbrains IDE with python plugin) so I don't need a complete beginner's guide but any information you can point to or give me for a jumping off point to get Maloja running in a way I can debug it would be very helpful.

EDIT: I stumbled my way into it but would still appreciate input. I will make a PR to the readme (or a developing.md file) after I have something more complete to add:

The directory specified by the env `MALOJA_DATA_DIRECTORY` must be populated with all folders from `maloja/data_files`. By default on linux this is `~/.local/share/maloja`

`pydevd.py --module ... --file maloja.server`

**Comment by krateng** [comment]
I'm not very good with making my own spaghetti code accessible to others unfortunately :D But if you have specific questions, feel free to ask, I'll try my best.

**Comment by studio-pastimes** [comment]
Any pointers on running this for development? I'd like to try out some changes for the frontend. Apologies if it's obvious and I've missed something!

**Comment by FoxxMD** [comment]
@studio-pastimes what I did (it's been a few months now)

1. setup a [virtual environment](https://docs.python.org/3/tutorial/venv.html)
2. install dependencies from project dir like `/path/to/virtualenv/bin/python -r /path/to/maloja/requirements.txt`
3. Need to populate folders like I mentioned in my original comment
4. run `path/to/virtualenv/bin/python -m maloja.server`
