### ISSUE TITLE
All pages showing things like \num1, 

### ISSUE THREAD

**Issue by helpimnotdrowning** [krateng/maloja#61]
All pages (/, /track, /charts_tracks, etc...) shows \num1, \num22 escapes instead of their respective symbols. The console shows this too, but I assume this is intentional.

**Comment by krateng** [comment]
Could you elaborate where it shows those?

**Comment by helpimnotdrowning** [comment]
![image](https://user-images.githubusercontent.com/35247379/101061124-c3e52a00-3555-11eb-99c2-2e8d90955f1f.png)
![image](https://user-images.githubusercontent.com/35247379/101061147-ca73a180-3555-11eb-9fc4-cb261b8a238d.png)
![image](https://user-images.githubusercontent.com/35247379/101061393-11fa2d80-3556-11eb-911b-a3f4b7f9c4fc.png)

also just realized the escape codes arent \numxx, but \num for \#

**Comment by krateng** [comment]
Are these scrobbles that you made from Maloja or imported from Last FM?

**Comment by krateng** [comment]
Ah, there is indeed a leftover in the conversion file. Should be fixed in the next version!
