### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by Extarys** [krateng/maloja#62]
Hi!
I wanted to use docker image on my RPi but it's amd64 only, so I was wondering if I install using `pip install malojaserver` how can I support multiple users? I wanted to use this with multi-scrobble but I'm not sure how I can set everything up for 2 users.

Thank you!

**Comment by krateng** [comment]
Each maloja instance is only intended for one user, so you'll have to run two servers. Generally I would do this with lxc containers or something similar, not sure how suitable the RasPi is for that. I haven't tried it, but technically you could also simply run two maloja processes on the same machine with different directories - something like:

`export MALOJA_DATA_DIRECTORY=/home/user/.local/share/maloja_user1/; maloja run`
`export MALOJA_DATA_DIRECTORY=/home/user/.local/share/maloja_user2/; maloja run`

Then you just set different ports in the two different folders and you should have two servers running.

**Comment by FoxxMD** [comment]
@Extarys For the multi-scrobbler side of things Im about to put out a new release that enables multi-user configurations from the app. Please check out the [`develop`](https://github.com/FoxxMD/multi-scrobbler/blob/develop/docs/configuration.md) branch and let me know if this makes sense and is useable for you.

**Comment by Extarys** [comment]
@FoxxMD I would need to test this on my local computer - I reinstalled my OS yesterday.
At first glace this looks like an acceptable compromise to have multi-user support.
