### ISSUE TITLE
allow speficying separate directories for configuration, state, cache, logs

### ISSUE THREAD

**Issue by Sohalt** [krateng/maloja#63]
Currently configuration, state (e.g. the database), cache, and logs all reside under the `DATA_DIR`, which defaults to `/etc/maloja`. It would be nice to be able to have these default to `/etc/maloja`, `/var/lib/maloja`, `/var/cache/maloja`, and `/var/log/maloja` respectively instead and be able to configure them separately to be abe to use things like https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=

**Comment by krateng** [comment]
Working on it, might take a bit to get an elegant and backwards-compatible solution though!

**Comment by Sohalt** [comment]
Thanks!
Probably something similar to the migration from `.local/share` to `/etc`, i.e. checking for the existence of files in the old location and otherwise using the new location would work.
Or maybe making a separate "migration", that actually moves the files to the new location. This should however not be done without explicit approval from the user.
