### ISSUE TITLE
Reliable import and export of maloja scrobbles database

### ISSUE THREAD

**Issue by NapeAddMew** [krateng/maloja#64]
Something that looks like `maloja import malojadatabase.zip` and `maloja export malojadatabase.zip`.

It's really important: I had a hell of a time importing v2.7 scrobbles to v.2.9, and then gave up and now use v2.8.5 (I _think_ there's some breaking changes there, but I am not that motivated to look).

**Comment by krateng** [comment]
What do you mean by importing 2.7 scrobbles to 2.9? They should just be the exact same files. Could you elaborate what errors / issues you encountered?

**Comment by NapeAddMew** [comment]
Well, I moved from an _old_ maloja version on Ubuntu to a rather new one on Manjaro. Manually copying and pasting the data files should have been a breeze, but I somehow find out that instead of putting them in `~/.local/share`, I need to put them in `~/.data`. Next, even after that, if I add scrobbles, maloja wouldn't start via `maloja start` and throw some dumb error regarding database. This is for v2.9 btw.

I downgraded to v2.8.5 and maloja somehow accepted the scrobbles without issue.

In fact, I just encountered a rather insane bug, where `maloja start` would return the following error:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/maloja", line 5, in <module>
    from maloja.proccontrol.control import main
ModuleNotFoundError: No module named 'maloja'
```

I "fixed" it by upgrading to the latest version. I have no idea what is going on tbh, but if it works in the end, that's what matters to me.

**Comment by krateng** [comment]
So is it now fully fixed with the latest version? Or does it still not start?

**Comment by NapeAddMew** [comment]
Oh it works, yeah. Sorry for not giving a clear bug report, btw. Next time I find a bug I'll do better.

BTW, do you have an email or something to contact you with? You don't even have a website so people can reach you.

**Comment by krateng** [comment]
I have maloja (at) krateng (dot) dev, but any issues regarding the software should just be posted here on GitHub.
