### ISSUE TITLE
belongtogether does not apply to existing records

### ISSUE THREAD

**Issue by linusboyle** [krateng/maloja#65]
Hi, I added some rules under the `rules` directory, but it does not take effect. 

I've tried to restart the process, or use the `rebuild library` function in admin panel. Looking into the logs nothing seems relevant. Somehow I'm sure the syntax is correct (copy&pasted).

the version is 2.11.0

**Comment by krateng** [comment]
Could you share the exact filename plus the contents of the file?

**Comment by linusboyle** [comment]
@krateng Hi I think I found the problem.

I added several `belongtogether` clauses, for example 

```
belongtogether  伍佰 & China Blue
```

they are always a band together but maloja takes it as two artists. It seems maloja does the split as soon as the scrobble request arrives, so the existing records cannot be reverted. I tried to scobble a new song just now, and it works like a charm.

So maybe it's more like a documentation problem :)

**Comment by linusboyle** [comment]
is it safe to edit the tsv files in `scrobbles` directory directly, so that I just need to search & replace in the existing records?

**Comment by krateng** [comment]
Ah yes, that rule doesn't affect existing scrobbles. Editing the tsv records is safe, but I'd make a backup just in case.

**Comment by linusboyle** [comment]
thanks, the problem is fixed now
