### ISSUE TITLE
Ability to delete / remove an artist and/or a track?

### ISSUE THREAD

**Issue by mannp** [krateng/maloja#67]
Hi there

Forgot and left my music running and played some tracks I'd prefer had not gotten scrobbled :)

Christmas tracks and the like that I'd prefer to remove from my scrobbles history.

Is there a gui way to remove them at all please?

Thanks in advance.

**Comment by krateng** [comment]
There's no GUI for it at the moment I'm afraid, you'd have to delete the according lines in the scrobble files (`/var/lib/maloja/scrobbles`, `/etc/maloja/scrobbles` or `~/.local/share/maloja/scrobbles`). I might attempt a GUI implementation, but can't promise anything.

**Comment by mannp** [comment]
Thanks for the information I needed in order to delete the unwanted scrobbles.

I have edited the files and needed to reboot the docker for them to come into effect, but the edits appear to have worked.

Any future gui would be much appreciated though if you find the time or inclination :)

I know its something lastfm would not allow and so the ability for maloja could be another positive reason to use it :)
