### ISSUE TITLE
manual scrobbling always split artist

### ISSUE THREAD

**Issue by linusboyle** [krateng/maloja#68]
Hi,

I added some `belongtogether` rules which works via api. But when I manually scrobble some tracks in the setting menu the artist is always split.

**Comment by krateng** [comment]
I fixed the outdated manual scrobbling code which I assume was the reason for this. Would you mind sharing an example for an artist combination for which this happens so I can test it?

**Comment by linusboyle** [comment]
@krateng Yes, I have a rule for a band called 'Emerson Lake & Palmer'. When I manually scrobble a track (the title does not matter), it becomes 'Emerson Lake &' and 'Palmer'.
