### ISSUE TITLE
Can't scrobble from android with Simple Scrobbler

### ISSUE THREAD

**Issue by helpimnotdrowning** [krateng/maloja#69]
The readme says that Maloja is compatible with Simple Scrobbler for android, but I cant get it to work. Im running Maloja through nginx for SSL, but when putting the details for the server in the GNU-FM server, SS instantly says "wrong username/password/token". Is there something else I should do? Ive installed the nginx certificate on my phone, port forwarded, and I can access the main page through Chrome android with https no problem.

Running:

- Maloja 2.12.5
- CPython 3.8.5
- Ubuntu 20.04 with WSL 2 on Windows 10 20H2
- Android 10
- Simple Scrobbler 1.7.0

**Comment by helpimnotdrowning** [comment]
Putting in anything for the username gets it stuck on "Authenticating..." instead of "wrong username/password/token".

**Comment by krateng** [comment]
Have you tried the Listenbrainz protocol (Simple Scrobbler supports that as well afaik)?

**Comment by helpimnotdrowning** [comment]
Putting it in the custom Listenbrainz thing takes a while to authenticate, but once it's done, SS never submits a scrobble, and manually pressing the "scrobble now" button doesnt do anything either.

**Comment by helpimnotdrowning** [comment]
Actually, I was ignoring this error that came up because some programs have problems when Windows has the command prompt to use UTF8, but a few minutes after trying to log in by GNUFM, these two `UnicodeDecodeError` exceptions pop up:
```pytb
Traceback (most recent call last):
  File "/home/owo/.local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/home/owo/.local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/owo/.local/lib/python3.8/site-packages/maloja/server.py", line 224, in static_html_public
    return static_html(name)
  File "/home/owo/.local/lib/python3.8/site-packages/maloja/server.py", line 229, in static_html
    keys = remove_identical(FormsDict.decode(request.query))
  File "/home/owo/.local/bin/bottle.py", line 1924, in decode
    copy.append(self._fix(key, enc), self._fix(value, enc))
  File "/home/owo/.local/bin/bottle.py", line 1910, in _fix
    return s.encode('latin1').decode(encoding or self.input_encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 4: invalid start byte
Traceback (most recent call last):
  File "/home/owo/.local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/home/owo/.local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/owo/.local/lib/python3.8/site-packages/maloja/server.py", line 224, in static_html_public
    return static_html(name)
  File "/home/owo/.local/lib/python3.8/site-packages/maloja/server.py", line 229, in static_html
    keys = remove_identical(FormsDict.decode(request.query))
  File "/home/owo/.local/bin/bottle.py", line 1924, in decode
    copy.append(self._fix(key, enc), self._fix(value, enc))
  File "/home/owo/.local/bin/bottle.py", line 1910, in _fix
    return s.encode('latin1').decode(encoding or self.input_encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 1: invalid continuation byte
```

Its the same 0xef and 0x8d everytime, so maybe it's a problem decoding the scrobble?

**Comment by krateng** [comment]
Can you scrobble at all? With another scrobbler, the manual scrobbling in the admin page or a direct curl request?

**Comment by helpimnotdrowning** [comment]
I think it might be a certificate problem on my end, manual scrobble on the admin panel works, a curl on Windows works, but a curl in WSL and on my phone fail because of an SSL problem.

**Comment by krateng** [comment]
Any updates on this? Is it Maloja-related or purely a certificate issue?

**Comment by helpimnotdrowning** [comment]
Yep, was just SSL.
