### ISSUE TITLE
Entry numbering confusion

### ISSUE THREAD

**Issue by nedludd** [krateng/maloja#70]
The artist thumbnails on the left side of the dashboard have a number next to the artist name.  Can you explain what this is?

My dashboard shows only the number 1 or 2.  See the attached screenshot.  Your example site seems to have consecutive numbering...

![Screenshot](https://user-images.githubusercontent.com/17875/110165401-e1c66300-7dc0-11eb-852e-de4833a6f731.png)

**Comment by krateng** [comment]
Those are the ranks in that time span. Artists or tracks with the same number of scrobbles have the same number, so I assume you've listened to Mana twice or more that day, to all other artists only once, hence making them all shared rank 2. Is that the case?

**Comment by nedludd** [comment]
Ah, I see.  Thanks.

Is there a way to turn that off?  I'm not really interested in the ranking.

**Comment by krateng** [comment]
Not at the moment, sorry.

**Comment by nedludd** [comment]
No worries.

Keep up the great work!
