### ISSUE TITLE
Support ratings

### ISSUE THREAD

**Issue by lyz-code** [krateng/maloja#72]
Hi, what an awesome service you've built, thanks!

I was wondering, will it be possible to register the user rating of a track? For example in the form of an integer from 1 to 5.

If you give me some guidelines, I can contribute with the backend part, as I have no idea of front.

**Comment by krateng** [comment]
Thanks for the suggestion - I'm afraid that's out of the scope of what I'd like this project to be though. Imho the scrobble numbers itself are supposed to indicate how much you like a track, and an additional rating would just add to the bloat.

**Comment by lyz-code** [comment]
I fully understand. In my case scrobble numbers are not representative enough as I usually randomly reproduce a lot of music I am discovering, but I know it's a corner case.

Thanks anyway :)
