### ISSUE TITLE
Duplicate scrobbles

### ISSUE THREAD

**Issue by ano95** [krateng/maloja#73]
Hello,

I noticed this problem while using [web-scrobbler](https://github.com/web-scrobbler/web-scrobbler/). WebScrobbler sends two requests per song using the native API v1:

- on the beginning (so called "now playing" scrobble)
- after listening to the song for some time

The second request contains `time` with unix timestamp of playback start (the first request doesn't contain `time`). The problem happens when server time for first request don't match time sent during the second request introducing duplicate scrobbles for one song.

Example of the resulting `.tsv` file in maloja:

```tsv
1620594473	artist	name	-	-
1620594472	artist	name	-	-
```

Maybe maloja could merge scrobbles that are few seconds apart? Or should this be fixed on the scrobbler side by sending `time` with first request as well?

**Comment by krateng** [comment]
Maloja does not support 'now playing', so the first scrobble shouldn't be sent at all.

**Comment by krateng** [comment]
Fixed in web-scrobbler/web-scrobbler@f543f5a1; thanks for taking the time!
