### ISSUE TITLE
Cannot access WEBUI?

### ISSUE THREAD

**Issue by nothing2obvi** [krateng/maloja#77]
Hello, I'd really like to use maloja but can't get it working either via docker or just via pip, both on a Mac and on an Ubuntu VM. I get through the setup just fine and enter all my API keys, but can't access the web UI. I've tried localhost and my host IP and no luck. Any ideas? Thanks!

**Comment by krateng** [comment]
Try starting with `maloja run`, what is the console output when you access the UI?

**Comment by nothing2obvi** [comment]
Hmm, I'm not getting anything indicating any type of error. For some reason I feel like it has to do with my port-mapping on docker? Using Portainer I've mapped out 42010 on both the host and container but not getting anything.

```
Various external services can be used to display images. If not enough of them are set up, only local images will be used.
        Currently not using a Last.fm API Key for image display.
        Currently not using a Fanart.tv API Key for image display.
        Currently not using a Spotify Client ID for image display.
        Currently not using a Spotify Client Secret for image display.
[thirdparty] MusicBrainz registered as metadata provider
[database] Starting database...
[database] Building database...
[database] Found 0 scrobbles...
Loading scrobbles |████████████████████████████████████████████████████████████████████████████████████████████████████| 100%                                                   
[database] Database loaded, optimizing...
[database] Database fully built!
[database] Authenticated Machines: Default Generated Key
[database] Database reachable!
[server] Starting up Maloja server...
[debug] Query Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
[debug] Aggregate Cache: 0 Perm Hits, 0 Tmp Hits, 0 Misses; Current Size: 0/0
```

**Comment by krateng** [comment]
If you use environment variables, they need the prefix `MALOJA_`, so e.g. `MALOJA_HOST` needs to be 0.0.0.0 if you access via IPv4. Is that the case?

**Comment by nothing2obvi** [comment]
Aahhh. That did it. Thanks so much for helping me out. From reading `settings.md` I didn't realize the prefix part. May I suggest some clarification on that for other people who may make my same mistake? Thanks again and I'm excited to finally use Maloja :)

![settings.md](https://user-images.githubusercontent.com/85228035/130536477-7cfed4d1-bbdc-4f45-bde0-b66bcb8781eb.png)

**Comment by krateng** [comment]
Good to hear! I added a small bit to the settings file to make it clearer.
