### ISSUE TITLE
Scrobbler in Edge does not retain settings

### ISSUE THREAD

**Issue by techie2000** [krateng/maloja#78]
I have installed the extension in Edge from the Chrome link. 
It installs without issue. 
I enter my local url/port and key. 
Both input boxes turn green. 
I play a track but it is not 'scrobbled'.
I check the settings on the extension and they have been reset to the original/default value.

**Comment by krateng** [comment]
Unfortunately I can't publish the latest version that should fix this at the moment, and Google is a bit vague on the reasons. For now, if you can manually install the scrobbler from this repository (enable developer mode in your Edge extensions, then use `load unpacked`), it should work. Alternatively, [Web Scrobbler](https://chrome.google.com/webstore/detail/web-scrobbler/hhinaapppaileiechjoiifaancjggfjm) should work fine with Maloja.

**Comment by techie2000** [comment]
Thanks. Let me know when the new version is online and I'll test it out too.

**Comment by krateng** [comment]
Looks like they have accepted the latest verison in the meantime - the web store version should work for now.
