### ISSUE TITLE
Any way to create custom themes?

### ISSUE THREAD

**Issue by nothing2obvi** [krateng/maloja#79]
I'm by no means an expert with any of this, but was just wondering if I wanted to create a custom theme for my maloja instance (and possibly share), is there a file I can edit to do so (I'm using docker btw)? Or would I only be able to accomplish this using something like a CSS injector browser extension? Thanks!

(sorry, not sure how to tag this as an enhancement)

**Comment by krateng** [comment]
There currently is no convenient way to do it server-side. Would you want to create a whole CSS theme or just change some colors via properties as @ZackBoe suggested?

**Comment by krateng** [comment]
I added a folder in the user settings where you can drop arbitrary css files to implement a custom theme. Changes should also now be a bit more convenient thanks to the use of CSS properties.

**Comment by gBasil** [comment]
> If you happen to make use of this, feel free to post a link or screenshot below - I'm interested what different designs people come up with!
@krateng

It's not much, but I tweaked the default theme a bit:

![SCR-20221201-wee](https://user-images.githubusercontent.com/57513430/205392545-273f6fb4-1125-4abe-876b-9b2dc0f7da11.png)
![SCR-20221201-wgf](https://user-images.githubusercontent.com/57513430/205392562-a061bbd4-7499-49ea-ab62-cf82815ece6a.png)

**Comment by VlaK0r** [comment]
> I added a folder in the user settings where you can drop arbitrary css files to implement a custom theme. Changes should also now be a bit more convenient thanks to the use of CSS properties.
> 
> If you happen to make use of this, feel free to post a link or screenshot below - I'm interested what different designs people come up with!

Please tell me, what am I doing wrong?
![изображение](https://github.com/user-attachments/assets/0f31f4a4-997a-447c-8ccf-1e70da8a0f5b)

In the folder, I created a file with a theme.
![изображение](https://github.com/user-attachments/assets/34fb1609-1695-4f15-8b40-09f7d83e4e5d)

But the theme does not change in any way.
