### ISSUE TITLE
Top Artists part of page never shows any images.

### ISSUE THREAD

**Issue by virtadpt** [krateng/maloja#8]
Hi.  I'm a relatively new user running commit 3c12462d36399588d60bdeec08dc7075f939ff4b on my server.  I'm trying to figure out why, on the Top Artists part of the page there are never any images displayed.  I'm running Maloja behind Nginx, which I suspect may have something to do with it but I'm not sure.

In case you want to take a look at what I'm seeing, here's my running install: https://chrysoprax.drwho.virtadpt.net/

I haven't had much time to mess with it lately so the only place you'd see anything is on the "All Time" part.

**Comment by krateng** [comment]
Which API keys have you added in your settings? IIRC Last.fm still offers track artwork, but not artist artwork, so it will only show artist images if you have also specified a Fanart.tv or Spotify API key.

**Comment by virtadpt** [comment]
I have API keys for last.fm and fanart.tv enabled.

**Comment by krateng** [comment]
Maybe it's a caching issue, try deleting the file cache/imgcache_artists in your maloja folder and then restart the server.

**Comment by virtadpt** [comment]
I just did so.  It did not seem to work.

**Comment by krateng** [comment]
Strange, I can't really think of any cause for this. One more thing you could try is shut down the server, delete the cache folder completely, update doreah to the latest version (`pip3 install doreah --upgrade --no-cache-dir`) and then start the server again. Do you have a custom settings.ini file or just the default settings?

**Comment by virtadpt** [comment]
Okay, giving it a try.
...
The only custom setting I have is `HOST="127.0.0.1"` because I'm proxying Maloja with Nginx so I can put it behind a subdomain.  Do you think that might have something to do with it?
...
Nope.  Didn't fix things.  Cache hasn't been recreated yet.

**Comment by krateng** [comment]
Well the weird thing is that your tracks have images, so I can't imagine any network settings on your end can really be responsible. But I checked your artists on my own maloja and they definitely get images.

If you manually make an API call, do you get a result? Try

`http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=Information Society&api_key=*{your key}*`
and
`http://webservice.fanart.tv/v3/music/051439e5-478e-4c03-8bea-774ad0c28c12?api_key=*{your key}*` from your server and see if you get an error.

**Comment by virtadpt** [comment]
First URL: It works.
Second URL: 500 Internal Server Error.  I've just pinged them on Twitter, but they haven't used their account since 2017 so it's unlikely they'll respond.
Going through the output of logwatch, I found the following in my Nginx logs:
```
    499 (undefined)
       /image?artist=Abney%20Park: 1 Time(s)
       /image?artist=Fiction%208: 1 Time(s)
       /image?artist=Information%20Society: 1 Time(s)
       /image?artist=Robert%20Anton%20Wilson: 1 Time(s)
       /image?artist=The%20Cr%C3%BCxshadows: 1 Time(s)
       /image?artist=ThouShaltNot: 1 Time(s)
```
That's why I was wondering if maybe it was an Nginx misconfiguration on my end.

**Comment by krateng** [comment]
I assume because the request takes too long, nginx 499s it, but normally it should still finish the request and then cache it for next time. Could you temporarily set your host to `0.0.0.0` and directly access your server via ip/port, just to check if this makes a difference?

**Comment by virtadpt** [comment]
I have done so - it does not make a difference.

**Comment by krateng** [comment]
Well, I'm lost. I'll add some logging output in the next version, maybe that helps find the problem.

**Comment by virtadpt** [comment]
Please let me know.  I'll deploy it and put it through its paces, and see what shakes out.

**Comment by krateng** [comment]
There is now some additional log output. Be aware that there has been a significant refactoring of Maloja, so you'll need to invoke the update command twice to get to the latest version; or reinstall it if you run into problems.

Once you run the new version, delete your old logs and then load your front page once so you have a clean log. You can then post the `external.log` here.

**Comment by virtadpt** [comment]
I've done so - there is no external.log file anymore.

Additionally, after updating I'm now getting a message
```
Currently installed Maloja version: 1.5.16
Latest recommended Maloja version: 2.1.2
Consider updating to take advantage of new features
```
on the /admin page.  I think I should give reinstalling a try after I get some sleep, I'm a bit jetlagged.

**Comment by krateng** [comment]
1.15.16 is the transition version, so updating once more should do the trick. If it doesn't and you do a new clean install, make sure to copy your scrobble / rule / etc files to ~/.local/share/maloja.

**Comment by virtadpt** [comment]
I've just given it a try with `./maloja update`, and no dice.  So I'm going to wipe it and try again.
...
Just did a full wipe and re-install of Maloja using the directions.  Same thing - nothing up top.  Looking in ~/.local/share/maloja/logs/external.log, I find the following:
```
2019/12/14 23:38:51  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:51  'mbid'
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:52  API: LastFM + Fanart.tv; Image request: Information Society
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:52  API: LastFM + Fanart.tv; Image request: 植松伸夫
2019/12/14 23:38:52  API: LastFM + Fanart.tv; Image request: Murray Gold
2019/12/14 23:38:52  API: LastFM + Fanart.tv; Image request: Covenant
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:52  API: LastFM + Fanart.tv; Image request: The Dreamside
2019/12/14 23:38:52  API: LastFM + Fanart.tv; Image request: Deltron 3030
2019/12/14 23:38:52  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:52  HTTP Error 401: Unauthorized
2019/12/14 23:38:53  Error while getting artist image from LastFM + Fanart.tv
2019/12/14 23:38:53  HTTP Error 401: Unauthorized
```
All over the place.  My ~/.local/share/maloja/settings/settings.ini file has my API keys in it.

**Comment by krateng** [comment]
Are you absolutely sure the API key is correct? That's really the only thing I can think of. Maybe also try to generate a new one regardless, apparently their API has had problems before.

**Comment by virtadpt** [comment]
I've just generated a project API key at fanart.tv (instead of a personal one).  Let's see if that works.
...
Nope.  Didn't work.  Not proxied through Nginx not going to port 42010 directly.  Is there anything in particular in the logs I should be looking for?

**Comment by krateng** [comment]
Did you restart maloja after changing the key in the settings file? And are the logs still showing Error 401 or something different?

**Comment by virtadpt** [comment]
I did.  I shut down Maloja, changed out the key, and then restarted it.  Let me try that again... also doing a `maloja update`... deleted the caches and the logs to make things easier to see... and it's partially fixed.

https://chrysoprax.drwho.virtadpt.net/

**Comment by krateng** [comment]
Yeah, it seems like the remaining missing ones simply are simply not covered by the APIs. You can add Spotify, that might add a few more artists. For me that's enough to get images for most artists, but I listen to fairly popular stuff, so YMMV.

Reworking the external image fetcher to be a bit more elegant and allow easier addition of custom API combinations is on the agenda, but low priority at the moment, so I can't promise anything.

**Comment by virtadpt** [comment]
Ah, well.  Guess I have to break down and set up a Spotify account.  Thanks for all your help.

**Comment by mannp** [comment]
> Ah, well. Guess I have to break down and set up a Spotify account. Thanks for all your help.

@virtadpt did setting up spotify work for you, as I have the same issue on my 2.9.10 instance.

I am not a fan of spotify, so will only do it if it works :+1:

**Comment by virtadpt** [comment]
It did not, and I kinda gave up.  Sorry.

**Comment by mannp** [comment]
> It did not, and I kinda gave up. Sorry.

Understand, thanks for responding :+1:

**Comment by mannp** [comment]
> It did not, and I kinda gave up. Sorry.

It resolved for me after creating the spotify account, deleting the cache directory for the app and rebooting the docker.

All the the artist images populated really quickly and seems fine.
