### ISSUE TITLE
Implement nativ scrobbling from MusicFolderPlayer

### ISSUE THREAD

**Issue by askurashev** [krateng/maloja#80]
Hello.
I use [MusicFolderPlayer](https://github.com/ltGuillaume/MusicFolderPlayer) for listen my music collection. I listen it by Chrome browser from PC and Android. 
How I connect Maloja and MusicFolderPlayer?

**Comment by krateng** [comment]
Does MusicFolderPlayer have any sort of scrobbling support? If it can scrobble to Listenbrainz or Libre.fm, you can use that API according to [the instructions](https://github.com/krateng/maloja#standard-compliant-api). If any scrobbler extension supports it, you can do the same there.

**Comment by krateng** [comment]
Closing this for now. Please create an issue with MusicFolderPlayer to enable basic scrobbling support - I'll happily help with implementing the Maloja-specifics on top of that.
