### ISSUE TITLE
listenbrainz scrobbling api issue with panoscrobbler

### ISSUE THREAD

**Issue by bayang** [krateng/maloja#86]
Hi, I try to use the listenbrainz endpoint with panoscrobbler on android but I can't get past authentication.

Pano refuses to validate my credentials.

I asked the pano dev and he answered me  : 

That server probably doesn't support https://listenbrainz.readthedocs.io/en/production/dev/api/#get--1-validate-token

Can you tell me if that endpoint from listenbrainz api is supported in maloja ?

Apparently I'm not the first one having issues with maloja and pano

https://github.com/krateng/maloja/issues/28

**Comment by krateng** [comment]
[The validate-token endpoint exists](https://github.com/krateng/maloja/blob/5157ce825eea9bf7b74123cb02dd28e25c6a0767/maloja/apis/listenbrainz.py#L65). Could you tell me your Maloja and Pano versions?

**Comment by bayang** [comment]
My maloja version is 2.12.14, pano version is 2.41 (sept 2021)

Btw I see differences between the url that is displayed in my instance setup page and the one displayed in the readme for listenbrainz api.

On my server I have : https://INSTNCE_HOST/api/s/listenbrainz 

In the readme : Your Maloja URL followed by /apis/listenbrainz

Notice the missing `/` between `api` and `s`

I tried both urls anyway in pano, and none works

**Comment by krateng** [comment]
Looks like the authentication request changed slightly, it should now work in 2.12.15

**Comment by bayang** [comment]
OK thanks a lot ! 

I'll try it when the docker image is updated.

**Comment by bayang** [comment]
I can confirm that it works with 2.12.15, thank you !
