### ISSUE TITLE
Images not showing up using Spotify/Lastfm API

### ISSUE THREAD

**Issue by AngerburN** [krateng/maloja#87]
Looks like i broke it. It used to work but know it looks like it needs a token? Using ID and secret key's for both even made new one's still nothing shows up.

```
[thirdparty] Could not get artist image for Baccara from LastFM
[thirdparty] Error getting artist image from Spotify: 'token'

[thirdparty] Could not get artist image for Baccara from MusicBrainz
[debug_performance] Generated page start in 1.01878s
[thirdparty] Error getting track image from LastFM: <urlopen error [Errno -3] Try again>

[thirdparty] Error getting track image from Spotify: 'token'

[thirdparty] Error getting track image from LastFM: <urlopen error [Errno -3] Try again>

[thirdparty] Error getting track image from Spotify: 'token'

[thirdparty] Error getting track image from LastFM: <urlopen error [Errno -3] Try again>

[thirdparty] Error getting track image from Spotify: 'token'

[thirdparty] Error getting track image from LastFM: <urlopen error [Errno -3] Try again>

[thirdparty] Error getting track image from Spotify: 'token'
```

**Comment by krateng** [comment]
Just to make sure, are your settings named `SPOTIFY_API_ID`, `SPOTIFY_API_SECRET` and `LASTFM_API_KEY`?

Also, what happens if you connect to the URL manually? 

https://ws.audioscrobbler.com/2.0/?method=track.getinfo&track=<title>&artist=<artist>&api_key=<your_lastfm_key>&format=json

**Comment by AngerburN** [comment]
`{"error":6,"message":"Track not found","links":[]}`

That's what it shows in my browser using my lastfm API key.

**Comment by krateng** [comment]
I added some log output to 2.12.16. Could you download the latest version, start up the server, go to the start page (or any page that causes an image error) and post the complete output from the start?

**Comment by AngerburN** [comment]
I'll need the updated docker otherwise i can't continue i'm on unraid.

**Comment by AngerburN** [comment]
`[thirdparty] Spotify registered as metadata provider
[thirdparty] MusicBrainz registered as metadata provider
[database] Starting database...
[database] Building database...
[database] Found 195 scrobbles...
[database] Database loaded, optimizing...
[maintenance] Sending daily stats report...
[database] Database fully built!
[database] Authenticated Machines: Default Generated Key
[database] Database reachable!
[server] Starting up Maloja server...
[debug_performance] Generated page start in 1.63622s
[debug_performance] Generated page start in 1.59134s
[debug_performance] Generated page start in 1.13130s
[debug] Query Cache: 88 Perm Hits, 23 Tmp Hits, 51 Misses; Current Size: 44/7
[debug] Aggregate Cache: 0 Perm Hits, 17 Tmp Hits, 13 Misses; Current Size: 0/13
[maintenance] Could not send daily report!
[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from Spotify: KeyError('token')

[thirdparty] Error getting track image from Spotify: KeyError('token')

[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from Spotify: KeyError('token')

[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from Spotify: KeyError('token')

[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from Spotify: KeyError('token')

[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from Spotify: KeyError('token')

[thirdparty] Could not get track image for (['Eminem'], 'Not Afraid') from MusicBrainz
[debug_performance] Generated page artist in 0.64361s
[thirdparty] Error getting track image from LastFM: URLError(gaierror(-3, 'Try again'))

[thirdparty] Error getting track image from Spotify: KeyError('token')`

Looks quite the same.

**Comment by krateng** [comment]
This is very strange. `[thirdparty] Spotify registered as metadata provider` means the Spotify class has been instantiated successfully, but that would mean it has at least tried to authenticate, which in every case should produce some log output.

As for the LastFM error, could you check if you can access LastFM at all from that container? Not sure how this works in Docker, but can you run curl / wget / etc in that same container to make sure there is no DNS problem or similar?

**Comment by AngerburN** [comment]
If i use wget inside the docker terminal i get a bad address error.

**Comment by krateng** [comment]
I would assume it's some sort of DNS problem for that container then. If troubleshooting that fails, you could set up a new container for maloja and copy over the data.

**Comment by AngerburN** [comment]
Well after some troubleshooting i decided to install with a fresh docker and just start over and remove the image and settings.
However know it just exits and fails to start. Ill wait until it's out of beta and it matures.

`Various external services can be used to display images. If not enough of them are set up, only local images will be used.
Currently not using a Last.fm API Key for image display.
Currently not using a Fanart.tv API Key for image display.
Currently not using a Spotify Client ID for image display.
Currently not using a Spotify Client Secret for image display.
sys.exit(main())
File "/usr/local/lib/python3.10/site-packages/doreah/control.py", line 47, in wrapper
return func(*args,**kwargs)
File "/usr/local/lib/python3.10/site-packages/maloja/proccontrol/control.py", line 89, in main
if action in actions: actions[action](*args,**kwargs)
File "/usr/local/lib/python3.10/site-packages/maloja/proccontrol/control.py", line 71, in direct
from .. import server
File "/usr/local/lib/python3.10/site-packages/maloja/server.py", line 13, in <module>
from . import database
File "/usr/local/lib/python3.10/site-packages/maloja/database.py", line 6, in <module>
from . import utilities
File "/usr/local/lib/python3.10/site-packages/maloja/utilities/__init__.py", line 1, in <module>
from .images import *
File "/usr/local/lib/python3.10/site-packages/maloja/utilities/images.py", line 3, in <module>
from .. import thirdparty
File "/usr/local/lib/python3.10/site-packages/maloja/thirdparty/__init__.py", line 216, in <module>
from . import *
File "/usr/local/lib/python3.10/site-packages/maloja/thirdparty/spotify.py", line 7, in <module>
class Spotify(MetadataInterface):
File "/usr/local/lib/python3.10/site-packages/maloja/thirdparty/__init__.py", line 77, in __init_subclass__
s = cls()
File "/usr/local/lib/python3.10/site-packages/maloja/thirdparty/__init__.py", line 73, in __init__
self.authorize()
File "/usr/local/lib/python3.10/site-packages/maloja/thirdparty/spotify.py", line 31, in authorize
"Authorization":"Basic " + b64(utf(self.settings["apiid"] + ":" + self.settings["secret"])).decode("utf-8")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by krateng** [comment]
Maloja is not in any kind of beta if that's what you mean. Error should be fixed now.
