### ISSUE TITLE
API availability during startup

### ISSUE THREAD

**Issue by FoxxMD** [krateng/maloja#88]
It is my understanding that the API is not available during application startup. Specifically, the API is not available until after the database has been built.

When building the database takes a long time (known issue from [here](https://github.com/krateng/maloja/issues/54) and more recently [here](https://github.com/FoxxMD/multi-scrobbler/issues/37#issuecomment-988527681)) it can appear as if Maloja is completely offline if someone tries to access an API endpoint.

I know it's not reasonable to expect a fully functioning API before the database is available, however would it be possible to start the web server before the database build and just return a [503 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) so that a user knows the application is working but unavailable?

**Comment by krateng** [comment]
I did some spaghetti reorganizing to enable that, but will still have to test this properly and clean up. Might take a few days!

**Comment by krateng** [comment]
Alright, I re-reorganized and it should work now in 2.12.18 hopefully without anything else breaking.
