### ISSUE TITLE
Any additional debug info?

### ISSUE THREAD

**Issue by pruperting** [krateng/maloja#98]
I've been totally failing to get scrobbling working with Maloja using Simple Scrobbler, Pano Scrobbler and Web Scrobbler.

When running Maloja via debug, I get this:

[apis] API request: ['submit-listens']
[debug_performance] Generated page admin_setup in 0.06726s
[debug_performance] Generated page admin_settings in 0.04298s
[debug_performance] Generated page admin_overview in 0.05549s
[debug_performance] Generated page start in 5.00954s
[debug_performance] Generated page start in 2.85772s
[apis] API request: ['submit-listens']
[apis] API request: ['submit-listens']

Implying a call is made, but then nothing else and I can't see any scrobbles via the web interface. Where else can I look to get more info as to what is failing when an attempt is made to scrobble to Maloja?

**Comment by pruperting** [comment]
I've been able to submit a scroble manually via the web interface and I've been able to submit a scrobble from a remote device using curl:

```
curl http://192.168.1.10:42010/apis/mlj_1/newscrobble -d "artist=value1&title=value2&key=faoA0waAaNd22p67QcAAachBXmNHebxC9R10wtdsC6BU2lFIrfCYNToAUqBzmX"
{"status": "success", "track": {"artists": ["value1"], "title": "value2"}}
```
But no luck with any of the supported scroblers and none of them give any useful error info to debug,

**Comment by krateng** [comment]
Can you build from source by any chance? The logs should now tell what's the error.

**Comment by pruperting** [comment]
Ahh cool, I should be able to, I'll give it a bash ;)

**Comment by pruperting** [comment]
Righty, finally managed to make some progressing after building from source. I assume I must be using the wrong settings for the "Maloja" account option in Web Scrobbler, that doesn't seem to work for me, but I was able to get the Listenbrainz option in Web Scrobbler to work. Also, I got the Maloja Scrobbler Chrome extension to also successfully submit a scrobble. 

I got rather confused by the instructions about which URLs to use for which services. The Listenbrainz instructions say you should use this: `/apis/listenbrainz` but this didn't work, however, I found an old post of yours which said to use this `/apis/listenbrainz/1/submit-listens` , and it did.

If interested, here is the stdout when scrobbling finally worked. Not sure what the 401 Listenbrainz error is about.
```

[apis] Error with Listenbrainz: {'code': 401, 'error': 'You need to provide an Authorization header.'} (<class 'maloja.apis._exceptions.BadAuthException'>)
[apis] Incoming scrobble (API: Listenbrainz): ARTISTS: Delta Heavy, TRACK: Kaleidoscope
[database] Database caches invalidated.
[apis] API request: ['submit-listens']
[debug_performance] Generated page start in 4.79476s
[thirdparty] Could not get artist image for Delta Heavy from LastFM
[thirdparty] Got artist image for Delta Heavy from Spotify
[thirdparty] Got track image for (['Delta Heavy'], 'Kaleidoscope') from LastFM
[debug_performance] Generated page start in 4.08675s
[apis] API request: ['submit-listens']
[apis] API request: ['submit-listens']
[apis] API request: ['submit-listens']
[apis] Error with Listenbrainz: {'code': 401, 'error': 'You need to provide an Authorization header.'} (<class 'maloja.apis._exceptions.BadAuthException'>)
[apis] Incoming scrobble (API: Listenbrainz): ARTISTS: prupert, TRACK: Hoover Song
[database] Database caches invalidated.
[debug_performance] Generated page start in 3.92979s
[thirdparty] Could not get artist image for prupert from LastFM
[thirdparty] Could not get artist image for prupert from Spotify
[thirdparty] Could not get track image for (['prupert'], 'Hoover Song') from LastFM
[thirdparty] Could not get track image for (['prupert'], 'Hoover Song') from Spotify
[thirdparty] Got artist image for prupert from Deezer
[thirdparty] Could not get track image for (['prupert'], 'Hoover Song') from Deezer
[debug_performance] Generated page start in 4.03281s
[thirdparty] Got track image for (['prupert'], 'Hoover Song') from MusicBrainz
[apis] API request: ['submit-listens']
[apis] API request: ['submit-listens']
[apis] Incoming scrobble (API: Listenbrainz): ARTISTS: High Contrast, TRACK: Days Go By (2019 Mix)
[apis] Error with Listenbrainz: {'code': 401, 'error': 'You need to provide an Authorization header.'} (<class 'maloja.apis._exceptions.BadAuthException'>)
```

**Comment by krateng** [comment]
Technically the provided URL should just be `/apis/listenbrainz`, but I of course can't control the individual scrobblers - some just demand the full endpoint as configuration.

So this is the stdout from when scrobbling worked?

**Comment by krateng** [comment]
Closing this for now as log error has no effect on functionality.
